import { Chapter, Term } from './types';

export const CHAPTERS: Chapter[] = [
  { id: '1.1', title: '1.1 Data Representation' },
  { id: '1.2', title: '1.2 Multimedia' },
  { id: '1.3', title: '1.3 File Compression' },
  { id: '2.1', title: '2.1 Networking' },
  { id: '2.2', title: '2.2 The Internet' },
  { id: '3.1', title: '3.1 Computers & Components' },
  { id: '3.2', title: '3.2 Logic Gates' },
  { id: '4.1', title: '4.1 CPU Architecture' },
  { id: '4.2', title: '4.2 Assembly Language' },
  { id: '4.3', title: '4.3 Bit Manipulation' },
  { id: '5.1', title: '5.1 Operating Systems' },
  { id: '5.2', title: '5.2 Language Translators' },
  { id: '6.1', title: '6.1 Data Security' },
  { id: '6.2', title: '6.2 Data Integrity' },
  { id: '7.1', title: '7.1 Legal, Moral & Ethical' },
  { id: '7.2', title: '7.2 Copyright Issues' },
  { id: '7.3', title: '7.3 Artificial Intelligence' },
  { id: '8.1', title: '8.1 Database Concepts' },
  { id: '8.2', title: '8.2 DBMS' },
  { id: '8.3', title: '8.3 DDL and DML' },
  { id: '9.1', title: '9.1 Computational Thinking' },
  { id: '9.2', title: '9.2 Algorithms' },
  { id: '10.1', title: '10.1 Data Types & Structures' },
  { id: '11.1', title: '11.1 Programming Basics' },
  { id: '11.3', title: '11.3 Structured Programming' },
  { id: '12.1', title: '12.1 Development Lifecycle' },
  { id: '12.2', title: '12.2 Program Design' },
  { id: '12.3', title: '12.3 Testing & Maintenance' },
];

let idCounter = 1;
const getNextId = () => (idCounter++).toString();

export const TERMS: Term[] = [
  // 1.1 Data Representation
  { id: getNextId(), chapterId: '1.1', term: 'Binary', definition: 'Base two number system based on the values 0 and 1 only.', aiExplanation: '二进制：一种仅使用0和1两个数字的计数系统，是计算机处理和存储数据的基础语言。' },
  { id: getNextId(), chapterId: '1.1', term: 'Bit', definition: 'Abbreviation for binary digit.', aiExplanation: '比特：二进制位的简称，是计算机中最小的信息单位，表示一个0或一个1。' },
  { id: getNextId(), chapterId: '1.1', term: "One's complement", definition: 'Each binary digit in a number is reversed to allow both negative and positive numbers to be represented.', aiExplanation: '反码：一种二进制数的表示法，通过将每一位（0变1，1变0）翻转来得到，用于表示负数。' },
  { id: getNextId(), chapterId: '1.1', term: "Two's complement", definition: 'Each binary digit is reversed and 1 is added in right-most position to produce another method of representing positive and negative numbers.', aiExplanation: '补码：在反码的基础上加1，是计算机系统中用于表示有符号整数的最常用方法，解决了0的符号问题。' },
  { id: getNextId(), chapterId: '1.1', term: 'Sign and magnitude', definition: 'Binary number system where left-most bit is used to represent the sign (0 = + and 1 = -); the remaining bits represent the binary value.', aiExplanation: '原码（符号-数值表示法）：最高位作为符号位（0正1负），其余位表示数值大小，直观但计算复杂。' },
  { id: getNextId(), chapterId: '1.1', term: 'Hexadecimal', definition: 'A number system based on the value 16 (uses the denary digits 0 to 9 and the letters A to F).', aiExplanation: '十六进制：基数为16的进位制，使用0-9和A-F表示，常用于简化二进制代码的显示和阅读。' },
  { id: getNextId(), chapterId: '1.1', term: 'Memory dump', definition: 'Contents of a computer memory output to screen or printer.', aiExplanation: '内存转储：将计算机内存中的数据完整地导出或打印出来，常用于调试程序错误。' },
  { id: getNextId(), chapterId: '1.1', term: 'Binary-coded decimal (BCD)', definition: 'Number system that uses 4 bits to represent each denary digit.', aiExplanation: '二进制编码的十进制（BCD）：用4位二进制数来分别表示十进制数中的每一位数字（0-9），常用于电子显示。' },
  { id: getNextId(), chapterId: '1.1', term: 'ASCII code', definition: 'Coding system for all the characters on a keyboard and control codes.', aiExplanation: 'ASCII码：一种字符编码标准，用数字来代表键盘上的字母、数字和符号，主要用于显示现代英语。' },
  { id: getNextId(), chapterId: '1.1', term: 'Character set', definition: 'A list of characters that have been defined by computer hardware and software. It is necessary to have a method of coding, so that the computer can understand human characters.', aiExplanation: '字符集：计算机能够识别和显示的所有字符的集合，每种字符集都有对应的编码规则（如ASCII或Unicode）。' },
  { id: getNextId(), chapterId: '1.1', term: 'Unicode', definition: 'Coding system which represents all the languages of the world (first 128 characters are the same as ASCII code).', aiExplanation: '统一码（Unicode）：一种全球通用的字符编码标准，旨在囊括世界上所有语言的字符，解决了乱码问题。' },

  // 1.2 Multimedia
  { id: getNextId(), chapterId: '1.2', term: 'Bit-map image', definition: 'System that uses pixels to make up an image.', aiExplanation: '位图图像：由一个个像素点组成的图像，放大后会失真（出现马赛克）。' },
  { id: getNextId(), chapterId: '1.2', term: 'Pixel', definition: 'Smallest picture element that makes up an image.', aiExplanation: '像素：构成数字图像的最小单位，每个像素包含颜色和亮度信息。' },
  { id: getNextId(), chapterId: '1.2', term: 'Colour depth', definition: 'Number of bits used to represent the colours in a pixel, e.g. 8 bit colour depth can represent 2^8 = 256 colours.', aiExplanation: '色彩深度：每个像素用来存储颜色信息的位数，位数越高，能显示的颜色越多，图像越逼真。' },
  { id: getNextId(), chapterId: '1.2', term: 'Bit depth', definition: 'Number of bits used to represent the smallest unit in, for example, a sound or image file – the larger the bit depth, the better the quality of the sound or colour image.', aiExplanation: '位深：多媒体文件中用于记录最小数据单元（如声音样本或像素颜色）的位数，直接影响文件的质量和大小。' },
  { id: getNextId(), chapterId: '1.2', term: 'Image resolution', definition: 'Number of pixels that make up an image, for example, an image could contain 4096 × 3192 pixels (12 738 656 pixels in total).', aiExplanation: '图像分辨率：图像包含的像素总数（宽x高），分辨率越高，图像越清晰，细节越丰富。' },
  { id: getNextId(), chapterId: '1.2', term: 'Screen resolution', definition: 'Number of horizontal and vertical pixels that make up a screen display. If the screen resolution is smaller than the image resolution, the whole image cannot be shown on the screen, or the original image will become lower quality.', aiExplanation: '屏幕分辨率：显示器屏幕上显示的像素点阵列（如1920x1080），决定了屏幕显示的清晰度和内容多少。' },
  { id: getNextId(), chapterId: '1.2', term: 'Resolution', definition: 'Number of pixels per column and per row on a monitor or television screen.', aiExplanation: '分辨率：通常指显示设备在水平和垂直方向上能显示的像素数量。' },
  { id: getNextId(), chapterId: '1.2', term: 'Pixel density', definition: 'Number of pixels per square centimetre.', aiExplanation: '像素密度：单位面积内的像素数量（如PPI），密度越高，画面越细腻，看不出颗粒感。' },
  { id: getNextId(), chapterId: '1.2', term: 'Vector graphics', definition: 'Images that use 2D points to describe lines and curves and their properties that are grouped to form geometric shapes.', aiExplanation: '矢量图形：使用数学公式（点、线、曲线）描述的图像，无论放大多少倍都不会失真，常用于Logo设计。' },
  { id: getNextId(), chapterId: '1.2', term: 'Sampling resolution', definition: 'Number of bits used to represent sound amplitude (also known as bit depth).', aiExplanation: '采样精度（位深）：数字音频中用于记录每一个声音样本振幅的位数，精度越高，声音动态范围越大，越接近原声。' },
  { id: getNextId(), chapterId: '1.2', term: 'Sampling rate', definition: 'Number of sound samples taken per second.', aiExplanation: '采样率：每秒钟对声音信号进行采集的次数（如44.1kHz），采样率越高，声音还原度越高。' },
  { id: getNextId(), chapterId: '1.2', term: 'Frame rate', definition: 'Number of video frames that make up a video per second.', aiExplanation: '帧率（FPS）：视频每秒播放的画面数量，帧率越高，视频动作越流畅。' },

  // 1.3 File Compression
  { id: getNextId(), chapterId: '1.3', term: 'Lossless file compression', definition: 'File compression method where the original file can be restored following decompression.', aiExplanation: '无损压缩：一种压缩后能完全还原原始数据的技术，不会丢失任何信息，如ZIP格式。' },
  { id: getNextId(), chapterId: '1.3', term: 'Lossy file compression', definition: 'File compression method where parts of the original file cannot be recovered during decompression, so some of the original detail is lost.', aiExplanation: '有损压缩：通过丢弃部分（通常是不重要的）数据来大幅减小文件体积的压缩方法，还原时无法与原件完全一致，如JPEG、MP3。' },
  { id: getNextId(), chapterId: '1.3', term: 'JPEG', definition: 'Joint Photographic Expert Group - a form of lossy file compression based on the inability of the eye to spot certain colour changes and hues.', aiExplanation: 'JPEG：一种广泛使用的有损图像压缩标准，利用人眼对色彩细节不敏感的特性来减小文件大小，适合照片。' },
  { id: getNextId(), chapterId: '1.3', term: 'MP3/MP4 files', definition: 'File compression method used for music and multimedia files.', aiExplanation: 'MP3/MP4：流行的音频和视频压缩格式，使用有损压缩技术在保持较好质量的同时大幅减小文件体积。' },
  { id: getNextId(), chapterId: '1.3', term: 'Audio compression', definition: 'Method used to reduce the size of a sound file using perceptual music shaping.', aiExplanation: '音频压缩：使用特定算法减少音频数据量的过程，便于存储和传输。' },
  { id: getNextId(), chapterId: '1.3', term: 'Perceptual music shaping', definition: 'Method where sounds outside the normal range of hearing of humans, for example, are eliminated from the music file during compression.', aiExplanation: '感知编码：一种音频压缩策略，通过删除人耳听不到或听不清楚的声音频率来减小文件大小。' },
  { id: getNextId(), chapterId: '1.3', term: 'Bit rate', definition: 'Number of bits per second that can be transmitted over a network. It is a measure of the data transfer rate over a digital telecoms network.', aiExplanation: '比特率（码率）：单位时间内传输或处理的比特数量，常用于衡量视频或音频的质量，码率越高，质量越好，文件越大。' },
  { id: getNextId(), chapterId: '1.3', term: 'Run length encoding (RLE)', definition: 'A lossless file compression technique used to reduce text and photo files in particular.', aiExplanation: '行程长度编码（RLE）：一种简单的无损压缩算法，将连续重复的数据（如AAAAA）替换为“数据+重复次数”（5A），适合压缩颜色简单的图像。' },

  // 2.1 Networking
  { id: getNextId(), chapterId: '2.1', term: 'ARPANet', definition: 'Advanced Research Projects Agency Network.', aiExplanation: '阿帕网：互联网的前身，是世界上第一个运营的封包交换网络。' },
  { id: getNextId(), chapterId: '2.1', term: 'WAN', definition: 'Wide area network (network covering a very large geographical area).', aiExplanation: '广域网 (WAN)：覆盖范围非常广（如跨城市、跨国家）的计算机网络，互联网就是最大的WAN。' },
  { id: getNextId(), chapterId: '2.1', term: 'LAN', definition: 'Local area network (network covering a small area such as a single building).', aiExplanation: '局域网 (LAN)：覆盖范围较小（如家庭、办公室、一栋楼）的计算机网络。' },
  { id: getNextId(), chapterId: '2.1', term: 'MAN', definition: 'Metropolitan area network (network which is larger than a LAN but smaller than a WAN, which can cover several buildings in a single city, such as a university campus).', aiExplanation: '城域网 (MAN)：覆盖范围介于LAN和WAN之间，通常覆盖一个城市或大学校园的网络。' },
  { id: getNextId(), chapterId: '2.1', term: 'File server', definition: 'A server on a network where central files and other data are stored. They can be accessed by a user logged onto the network.', aiExplanation: '文件服务器：网络中专门用于存储和管理共享文件的计算机，供网络用户访问和下载。' },
  { id: getNextId(), chapterId: '2.1', term: 'Hub', definition: 'Hardware used to connect together a number of devices to form a LAN that directs incoming data packets to all devices on the network (LAN).', aiExplanation: '集线器：一种基础网络设备，将收到的数据包广播发给连接在它上面的所有设备，效率较低。' },
  { id: getNextId(), chapterId: '2.1', term: 'Switch', definition: 'Hardware used to connect together a number of devices to form a LAN that directs incoming data packets to a specific destination address only.', aiExplanation: '交换机：一种智能网络设备，能识别设备地址，只把数据包发给指定的目标设备，比集线器效率高。' },
  { id: getNextId(), chapterId: '2.1', term: 'Router', definition: 'Device which enables data packets to be routed between different networks (e.g. joining LANs to form a WAN).', aiExplanation: '路由器：连接不同网络（如连接家庭LAN和互联网WAN）的设备，负责寻找数据传输的最佳路径。' },
  { id: getNextId(), chapterId: '2.1', term: 'Modem', definition: 'Modulator demodulator. A device that converts digital data to analogue data (to be sent down a telephone wire); conversely it also converts analogue data to digital data (which a computer can process).', aiExplanation: '调制解调器（猫）：负责数字信号（电脑用）和模拟信号（电话线/光纤用）之间的转换，是上网的必备设备。' },
  { id: getNextId(), chapterId: '2.1', term: 'WLAN', definition: 'Wireless LAN.', aiExplanation: '无线局域网：利用无线电波技术（如Wi-Fi）构建的局域网，无需网线连接。' },
  { id: getNextId(), chapterId: '2.1', term: '(W)AP', definition: '(Wireless) access point which allows a device to access a LAN without a wired connection.', aiExplanation: '无线接入点 (AP)：提供无线信号的设备，让手机电脑能通过Wi-Fi连接到有线网络。' },
  { id: getNextId(), chapterId: '2.1', term: 'PAN', definition: 'Network that is centred around a person or their workspace.', aiExplanation: '个人局域网 (PAN)：以个人为中心的短距离网络，如手机通过蓝牙连接耳机或智能手表。' },
  { id: getNextId(), chapterId: '2.1', term: 'Client-server', definition: 'Network that uses separate dedicated servers and specific client workstations. All client computers are connected to the dedicated servers.', aiExplanation: '客户机-服务器模式：一种网络架构，由强大的服务器提供资源，客户端电脑发出请求并使用资源。' },
  { id: getNextId(), chapterId: '2.1', term: 'Spread spectrum technology', definition: 'Wideband radio frequency with a range of 30 to 50 metres.', aiExplanation: '扩频技术：一种无线通信技术，将信号散布在更宽的频带上以减少干扰和提高安全性。' },
  { id: getNextId(), chapterId: '2.1', term: 'Node', definition: 'Device connected to a network (it can be a computer, storage device or peripheral device).', aiExplanation: '节点：连接到网络中的任何设备，如电脑、打印机或路由器。' },
  { id: getNextId(), chapterId: '2.1', term: 'Peer-to-peer', definition: 'Network in which each node can share its files with all the other nodes. Each node has its own data and there is no central server.', aiExplanation: '点对点网络 (P2P)：没有中心服务器，所有电脑地位平等，既是客户端也是服务器，直接互相分享资源。' },
  { id: getNextId(), chapterId: '2.1', term: 'Thin client', definition: 'Device that needs access to the internet for it to work and depends on a more powerful computer for processing.', aiExplanation: '瘦客户端：性能较弱的终端设备，主要依靠连接服务器来进行计算和存储，如云桌面终端。' },
  { id: getNextId(), chapterId: '2.1', term: 'Thick client', definition: 'Device which can work both off line and on line and is able to do some processing even if not connected to a network/internet.', aiExplanation: '胖客户端：功能完整的电脑（如普通PC），即使断网也能独立运行大部分程序。' },
  { id: getNextId(), chapterId: '2.1', term: 'Bus network topology', definition: 'Network using single central cable in which all devices are connected to this cable so data can only travel in one direction and only one device is allowed to transmit at a time.', aiExplanation: '总线型拓扑：所有设备连接到同一条主电缆（总线）上，结构简单但容易冲突，一处断裂可能导致全网瘫痪。' },
  { id: getNextId(), chapterId: '2.1', term: 'Packet', definition: 'Message/data sent over a network from node to node (packets include the address of the node sending the packet, the address of the packet recipient and the actual data - this is covered in greater depth in Chapter 14).', aiExplanation: '数据包：网络传输的基本数据单元，包含数据内容以及发送和接收地址等控制信息。' },
  { id: getNextId(), chapterId: '2.1', term: 'Star network topology', definition: 'A network that uses a central hub/switch with all devices connected to this central hub/switch so all data packets are directed through this central hub/switch.', aiExplanation: '星型拓扑：所有设备都连接到一个中心节点（交换机/集线器），易于管理和排错，是目前最常用的局域网结构。' },
  { id: getNextId(), chapterId: '2.1', term: 'Mesh network topology', definition: 'Interlinked computers/devices which use routing logic so data packets are sent from sending stations to receiving stations only by the shortest route.', aiExplanation: '网状拓扑：设备之间有多条连接路径，可靠性极高，如果一条路断了可以走另一条，常用于互联网核心或军用网络。' },
  { id: getNextId(), chapterId: '2.1', term: 'Hybrid network', definition: 'Network made up of a combination of other network topologies.', aiExplanation: '混合拓扑：结合了星型、总线型或环型等多种结构的复杂网络。' },
  { id: getNextId(), chapterId: '2.1', term: 'Cloud storage', definition: 'Method of data storage where data is stored on off-site servers.', aiExplanation: '云存储：将数据通过网络存储在远程服务器上，而非本地硬盘，方便随时随地访问和备份。' },
  { id: getNextId(), chapterId: '2.1', term: 'Data redundancy', definition: 'Situation in which the same data is stored on several servers in case of maintenance or repair.', aiExplanation: '数据冗余：在不同地方存储多份相同的数据副本，以防止数据丢失，提高系统可靠性。' },
  { id: getNextId(), chapterId: '2.1', term: 'Wi-Fi', definition: 'Wireless connectivity that uses radio waves, microwaves. Implements IEEE 802.11 protocols.', aiExplanation: 'Wi-Fi：一种基于IEEE 802.11标准的无线局域网技术，让设备通过无线电波联网。' },
  { id: getNextId(), chapterId: '2.1', term: 'Bluetooth', definition: 'Wireless connectivity that uses radio waves in the 2.45 GHz frequency band.', aiExplanation: '蓝牙：一种短距离无线通信技术，常用于连接耳机、鼠标、键盘等外设。' },
  { id: getNextId(), chapterId: '2.1', term: 'Spread spectrum frequency hopping', definition: 'A method of transmitting radio signals in which a device picks one of 79 channels at random. If the chosen channel is already in use, it randomly chooses another channel. It has a range up to 100 metres.', aiExplanation: '跳频扩频：发送端和接收端按同步规律快速切换频率，以抗干扰和防窃听，蓝牙技术就使用了此原理。' },
  { id: getNextId(), chapterId: '2.1', term: 'WPAN', definition: 'Wireless personal area network. A local wireless network which connects together devices in very close proximity (such as in a user\'s house); typical devices would be a laptop, smartphone, tablet and printer.', aiExplanation: '无线个人局域网：小范围（通常10米内）的无线网络，用于连接个人设备。' },
  { id: getNextId(), chapterId: '2.1', term: 'Twisted pair cable', definition: 'Type of cable in which two wires of a single circuit are twisted together. Several twisted pairs make up a single cable.', aiExplanation: '双绞线：两根绝缘铜线绞合在一起以抵消电磁干扰，是目前最常用的以太网网线。' },
  { id: getNextId(), chapterId: '2.1', term: 'Coaxial cable', definition: 'Cable made up of central copper core, insulation, copper mesh and outer insulation.', aiExplanation: '同轴电缆：一种中心是铜芯，外包绝缘层和屏蔽网的线缆，以前用于有线电视和早期网络。' },
  { id: getNextId(), chapterId: '2.1', term: 'Fibre optic cable', definition: 'Cable made up of glass fibre wires which use pulses of light (rather than electricity) to transmit data.', aiExplanation: '光纤：利用玻璃纤维内的光脉冲来传输数据，速度极快，传输距离远，不受电磁干扰。' },
  { id: getNextId(), chapterId: '2.1', term: 'Gateway', definition: 'Device that connects LANs which use different protocols.', aiExplanation: '网关：连接两个使用不同通信协议的网络的翻译设备，确保它们能互相通信。' },
  { id: getNextId(), chapterId: '2.1', term: 'Repeater', definition: 'Device used to boost a signal on both wired and wireless networks.', aiExplanation: '中继器：接收微弱信号并放大发送的设备，用于延长网络信号的传输距离。' },
  { id: getNextId(), chapterId: '2.1', term: 'Repeating hubs', definition: 'Network devices which are a hybrid of hub and repeater unit.', aiExplanation: '中继集线器：具有信号放大功能的集线器。' },
  { id: getNextId(), chapterId: '2.1', term: 'Bridge', definition: 'Device that connects LANs which use the same protocols.', aiExplanation: '网桥：连接两个使用相同协议的局域网片段的设备，可以隔离冲突域。' },
  { id: getNextId(), chapterId: '2.1', term: 'Softmodem', definition: 'Abbreviation for software modem; a software-based modem that uses minimal hardware.', aiExplanation: '软猫：利用电脑CPU处理信号转换的调制解调器，硬件简单但占用系统资源。' },
  { id: getNextId(), chapterId: '2.1', term: 'NIC', definition: 'Network interface card. These cards allow devices to connect to a network/internet (usually associated with a MAC address set at the factory).' },
  { id: getNextId(), chapterId: '2.1', term: 'WNIC', definition: 'Wireless network interface cards/controllers.', aiExplanation: '无线网卡：让电脑能连接Wi-Fi网络的硬件设备。' },
  { id: getNextId(), chapterId: '2.1', term: 'Ethernet', definition: 'Protocol IEEE 802.3 used by many wired LANs.', aiExplanation: '以太网：最通用的有线局域网标准协议（IEEE 802.3）。' },
  { id: getNextId(), chapterId: '2.1', term: 'Conflict', definition: 'Situation in which two devices have the same IP address.', aiExplanation: 'IP冲突：两个设备被分配了相同的IP地址，导致网络连接异常。' },
  { id: getNextId(), chapterId: '2.1', term: 'Broadcast', definition: 'Communication where pieces of data are sent from sender to receiver.', aiExplanation: '广播：向网络中所有设备发送数据的通信方式。' },
  { id: getNextId(), chapterId: '2.1', term: 'Collision', definition: 'Situation in which two messages/data from different sources are trying to transmit along the same data channel.', aiExplanation: '冲突/碰撞：两个设备同时尝试在同一信道发送数据，导致信号混淆。' },
  { id: getNextId(), chapterId: '2.1', term: 'CSMA/CD', definition: 'Carrier sense multiple access with collision detection – a method used to detect collisions and resolve the issue.', aiExplanation: '载波监听多路访问/冲突检测：以太网用于管理数据发送规则的协议，“先听后发，边发边听，冲突停止”。' },
  { id: getNextId(), chapterId: '2.1', term: 'Bit streaming', definition: 'Contiguous sequence of digital bits sent over a network/internet.', aiExplanation: '比特流：连续不断的数字信号传输，常用于流媒体。' },
  { id: getNextId(), chapterId: '2.1', term: 'Buffering', definition: 'Store which holds data temporarily.', aiExplanation: '缓冲：在播放视频或音频前预先下载一部分数据到内存，以防止播放卡顿。' },
  { id: getNextId(), chapterId: '2.1', term: 'On demand (bit streaming)', definition: 'System that allows users to stream video or music files from a central server as and when required without having to save the files on their own computer/tablet/phone.', aiExplanation: '点播：用户可以随时请求播放服务器上的音视频内容，而不需要下载整个文件。' },
  { id: getNextId(), chapterId: '2.1', term: 'Real-time (bit streaming)', definition: 'System in which an event is captured by camera (and microphone) connected to a computer and sent to a server where the data is encoded. The user can access the data \'as it happens\' live.', aiExplanation: '实时流媒体（直播）：边录制、边传输、边播放的技术，用户看到的画面几乎与现场同步。' },

  // 2.2 The Internet
  { id: getNextId(), chapterId: '2.2', term: 'Internet', definition: 'Massive network of networks, made up of computers and other electronic devices; uses TCP/IP communication protocols.', aiExplanation: '互联网：全球最大的互联网络，连接了全世界的计算机，使用TCP/IP协议。' },
  { id: getNextId(), chapterId: '2.2', term: 'World Wide Web (WWW)', definition: 'Collection of multimedia web pages stored on a website, which uses the internet to access information from servers and other computers.', aiExplanation: '万维网：运行在互联网上的网页服务，包含无数的网页和超链接，通常通过浏览器访问。' },
  { id: getNextId(), chapterId: '2.2', term: 'HyperText Mark-up Language (HTML)', definition: 'Used to design web pages and to write http(s) protocols, for example.', aiExplanation: '超文本标记语言 (HTML)：制作网页的标准语言，用于定义网页的结构和内容。' },
  { id: getNextId(), chapterId: '2.2', term: 'Uniform resource locator (URL)', definition: 'Specifies location of a web page (for example, www.hoddereducation.co.uk).', aiExplanation: '统一资源定位符 (URL)：网页地址（网址），告诉浏览器去哪里找特定的网页资源。' },
  { id: getNextId(), chapterId: '2.2', term: 'Web browser', definition: 'Software that connects to DNS to locate IP addresses; interprets web pages sent to a user\'s computer so that documents and multimedia can be read or watched/listened to.', aiExplanation: '网页浏览器：用于检索、显示和浏览网页内容的软件，如Chrome、Edge。' },
  { id: getNextId(), chapterId: '2.2', term: 'Internet service provider (ISP)', definition: 'Company which allows a user to connect to the internet. They will usually charge a monthly fee for the service they provide.', aiExplanation: '互联网服务提供商 (ISP)：提供上网服务的公司，如电信、移动、联通。' },
  { id: getNextId(), chapterId: '2.2', term: 'Public switched telephone network (PSTN)', definition: 'Network used by traditional telephones when making calls or when sending faxes.', aiExplanation: '公共交换电话网：传统的有线电话网络。' },
  { id: getNextId(), chapterId: '2.2', term: 'Voice over Internet Protocol (VoIP)', definition: 'Converts voice and webcam images into digital packages to be sent over the internet.', aiExplanation: '网络语音电话 (VoIP)：通过互联网进行语音通话的技术，如Skype、微信语音。' },
  { id: getNextId(), chapterId: '2.2', term: 'Internet protocol (IP)', definition: 'Uses IPv4 or IPv6 to give addresses to devices connected to the internet.', aiExplanation: '网际协议 (IP)：为网络设备分配地址并规定数据包如何路由的协议。' },
  { id: getNextId(), chapterId: '2.2', term: 'IPv4', definition: 'IP address format which uses 32 bits, such as 200.21.100.6.', aiExplanation: 'IPv4：第四版IP地址，由4组数字组成（如192.168.1.1），地址资源已近枯竭。' },
  { id: getNextId(), chapterId: '2.2', term: 'Classless inter-domain routing (CIDR)', definition: 'Increases IPv4 flexibility by adding a suffix to the IP address, such as 200.21.100.6/18.', aiExplanation: '无类别域间路由 (CIDR)：一种更灵活的IP地址分配方法，用斜杠后缀表示子网掩码长度。' },
  { id: getNextId(), chapterId: '2.2', term: 'IPv6', definition: 'Newer IP address format which uses 128 bits, such as A8F0:7FFF:F0F1:F000:3DD0:256A:22FF:AA00.', aiExplanation: 'IPv6：第六版IP地址，由长串16进制数组成，提供了几乎无限的地址空间。' },
  { id: getNextId(), chapterId: '2.2', term: 'Zero compression', definition: 'Way of reducing the length of an IPv6 address by replacing groups of zeroes by a double colon (::); this can only be applied once to an address to avoid ambiguity.', aiExplanation: '零压缩：IPv6地址简写规则，连续的0可以用双冒号“::”代替，但只能用一次。' },
  { id: getNextId(), chapterId: '2.2', term: 'Sub-netting', definition: 'Practice of dividing networks into two or more sub-networks.', aiExplanation: '子网划分：将一个大的网络划分成多个较小的逻辑网络，以提高性能和安全性。' },
  { id: getNextId(), chapterId: '2.2', term: 'Private IP address', definition: 'An IP address reserved for internal network use behind a router.', aiExplanation: '私有IP地址：仅在局域网内部使用的IP地址，不能直接在互联网上访问。' },
  { id: getNextId(), chapterId: '2.2', term: 'Public IP address', definition: 'An IP address allocated by the user\'s ISP to identify the location of their device on the internet.', aiExplanation: '公网IP地址：全球唯一的IP地址，用于在互联网上标识设备。' },
  { id: getNextId(), chapterId: '2.2', term: 'Domain name service (DNS)', definition: '(Also known as domain name system) gives domain names for internet hosts and is a system for finding IP addresses of a domain name.', aiExplanation: '域名系统 (DNS)：互联网的电话簿，负责将易记的域名（如google.com）翻译成电脑能懂的IP地址。' },
  { id: getNextId(), chapterId: '2.2', term: 'JavaScript', definition: 'Object-orientated (or scripting) programming language used mainly on the web to enhance HTML pages.', aiExplanation: 'JavaScript：一种运行在浏览器中的脚本语言，用于让网页具有交互性和动态效果。' },
  { id: getNextId(), chapterId: '2.2', term: 'PHP', definition: 'Hypertext processor; an HTML-embedded scripting language used to write web pages.', aiExplanation: 'PHP：一种广泛使用的服务器端脚本语言，常用于开发动态网站。' },

  // 3.1 Computers and their components
  { id: getNextId(), chapterId: '3.1', term: 'Memory cache', definition: 'High speed memory external to processor which stores data which the processor will need again.', aiExplanation: '高速缓存：位于CPU和内存之间的高速小容量存储器，用于存放常用数据以加快处理速度。' },
  { id: getNextId(), chapterId: '3.1', term: 'Random access memory (RAM)', definition: 'Primary memory unit that can be written to and read from. Volatile.', aiExplanation: '随机存取存储器 (RAM)：电脑的内存，运行程序时临时存放数据，断电后数据丢失（易失性）。' },
  { id: getNextId(), chapterId: '3.1', term: 'Read-only memory (ROM)', definition: 'Primary memory unit that can only be read from. Non-volatile.', aiExplanation: '只读存储器 (ROM)：只能读取不能写入的存储器，断电数据不丢失，常用于存储开机程序（BIOS）。' },
  { id: getNextId(), chapterId: '3.1', term: 'Programmable ROM (PROM)', definition: 'Type of ROM chip that can be programmed once.', aiExplanation: '可编程ROM：一种出厂为空白，用户可以写入一次数据但之后无法更改的ROM。' },
  { id: getNextId(), chapterId: '3.1', term: 'Erasable PROM (EPROM)', definition: 'Type of ROM that can be programmed more than once using ultraviolet (UV) light.', aiExplanation: '可擦除PROM：可以用紫外线照射来擦除数据并重新编程的ROM。' },
  { id: getNextId(), chapterId: '3.1', term: 'Hard disk drive (HDD)', definition: 'Type of magnetic storage device that uses spinning disks.', aiExplanation: '机械硬盘：利用旋转的磁盘和磁头读写数据的传统存储设备，容量大但速度较慢。' },
  { id: getNextId(), chapterId: '3.1', term: 'Latency', definition: 'The lag in a system; for example, the time to find a track on a hard disk, which depends on the time taken for the disk to rotate around to its read-write head.', aiExplanation: '延迟：数据请求发出到实际传输开始的等待时间，在机械硬盘中主要指磁盘旋转到正确位置的时间。' },
  { id: getNextId(), chapterId: '3.1', term: 'Fragmented', definition: 'Storage of data in non-consecutive sectors; for example, due to editing and deletion of old data.', aiExplanation: '碎片化：文件数据被分散存储在磁盘不连续的区域，会导致读取速度变慢。' },
  { id: getNextId(), chapterId: '3.1', term: 'Removable hard disk drive', definition: 'Portable hard disk drive that is external to the computer; it can be connected via a USB port when required; often used as a device to backup files and data.', aiExplanation: '移动硬盘：便携式的大容量存储设备，常用于备份和传输大量数据。' },
  { id: getNextId(), chapterId: '3.1', term: 'Solid state drive (SSD)', definition: 'Storage media with no moving parts that relies on movement of electrons.', aiExplanation: '固态硬盘：使用闪存芯片存储数据的设备，无机械结构，速度比HDD快得多，抗震且静音。' },
  { id: getNextId(), chapterId: '3.1', term: 'Electronically erasable programmable read-only memory (EEPROM)', definition: 'Read-only (ROM) chip that can be modified by the user, which can then be erased and written to repeatedly using pulsed voltages.', aiExplanation: '电可擦除PROM：可以用电信号擦除和重写的ROM，现在的BIOS芯片多用此类。' },
  { id: getNextId(), chapterId: '3.1', term: 'Flash memory', definition: 'A type of EEPROM, particularly suited to use in drives such as SSDs, memory cards and memory sticks.', aiExplanation: '闪存：一种非易失性存储技术，广泛用于U盘、SD卡和固态硬盘。' },
  { id: getNextId(), chapterId: '3.1', term: 'Optical storage', definition: 'CDs, DVDs and Blu-ray™ discs that use laser light to read and write data.', aiExplanation: '光存储：利用激光读取盘片凹坑来存储数据的技术，如光盘。' },
  { id: getNextId(), chapterId: '3.1', term: 'Dual layering', definition: 'Used in DVDs; uses two recording layers.', aiExplanation: '双层刻录：在光盘的一面上制作两个数据层，使存储容量翻倍。' },
  { id: getNextId(), chapterId: '3.1', term: 'Birefringence', definition: 'A reading problem with DVDs caused by refraction of laser light into two beams.', aiExplanation: '双折射：光盘读取中的一种光学问题，激光束被折射成两束，可能导致读取错误。' },
  { id: getNextId(), chapterId: '3.1', term: 'Binder 3D printing', definition: '3D printing method that uses a two-stage pass; the first stage uses dry powder and the second stage uses a binding agent.', aiExplanation: '粘合剂喷射3D打印：通过喷射胶水粘合粉末材料逐层堆叠成型的打印技术。' },
  { id: getNextId(), chapterId: '3.1', term: 'Dynamic RAM (DRAM)', definition: 'Type of RAM chip that needs to be constantly refreshed.', aiExplanation: '动态RAM：最常见的内存类型，利用电容存储电荷，需要不断刷新电路才能保持数据。' },
  { id: getNextId(), chapterId: '3.1', term: 'Static RAM (SRAM)', definition: 'Type of RAM chip that uses flip-flops and does not need refreshing.', aiExplanation: '静态RAM：速度极快且不需要刷新的内存，常用于CPU缓存，但造价昂贵。' },
  { id: getNextId(), chapterId: '3.1', term: 'Refreshed', definition: 'Requirement to charge a component to retain its electronic state.', aiExplanation: '刷新：对动态内存（DRAM）定期充电以防止数据丢失的过程。' },
  { id: getNextId(), chapterId: '3.1', term: 'Direct 3D printing', definition: '3D printing technique where print head moves in the x, y and z directions. Layers of melted material are built up using nozzles like an inkjet printer.', aiExplanation: '直接3D打印：打印头在三维空间移动，通过喷嘴挤出熔化材料逐层构建物体的技术（类似FDM）。' },
  { id: getNextId(), chapterId: '3.1', term: 'Digital to analogue converter (DAC)', definition: 'Needed to convert digital data into electric currents that can drive motors, actuators and relays, for example.', aiExplanation: '数模转换器 (DAC)：将计算机的数字信号转换为模拟信号（如声音电流）的设备。' },
  { id: getNextId(), chapterId: '3.1', term: 'Analogue to digital converter (ADC)', definition: 'Needed to convert analogue data (read from sensors, for example) into a form understood by a computer.', aiExplanation: '模数转换器 (ADC)：将现实世界的模拟信号（如声音、温度电压）转换为计算机能处理的数字信号。' },
  { id: getNextId(), chapterId: '3.1', term: 'Organic LED (OLED)', definition: 'Uses movement of electrons between cathode and anode to produce an on-screen image. It generates its own light so no back lighting required.', aiExplanation: '有机发光二极管 (OLED)：一种自发光的显示技术，不需要背光，对比度高，色彩鲜艳，且屏幕可以弯曲。' },
  { id: getNextId(), chapterId: '3.1', term: 'Screen resolution', definition: 'Number of pixels in the horizontal and vertical directions on a television/computer screen.', aiExplanation: '屏幕分辨率：屏幕上横向和纵向的像素点总数。' },
  { id: getNextId(), chapterId: '3.1', term: 'Touch screen', definition: 'Screen on which the touch of a finger or stylus allows selection or manipulation of a screen image; they usually use capacitive or resistive technology.', aiExplanation: '触摸屏：既是显示设备也是输入设备，允许用户直接用手指操作界面。' },
  { id: getNextId(), chapterId: '3.1', term: 'Capacitive', definition: 'Type of touch screen technology based on glass layers forming a capacitor, where fingers touching the screen cause a change in the electric field.', aiExplanation: '电容式触摸屏：利用人体电流感应工作的屏幕，触控灵敏，支持多点触控（如现代手机屏幕）。' },
  { id: getNextId(), chapterId: '3.1', term: 'Resistive', definition: 'Type of touch screen technology. When a finger touches the screen, the glass layer touches the plastic layer, completing the circuit and causing a current to flow at that point.', aiExplanation: '电阻式触摸屏：靠压力感应工作的屏幕，需要按压才能识别，精度高但不支持多点触控（老式PDA或ATM）。' },
  { id: getNextId(), chapterId: '3.1', term: 'Virtual reality headset', definition: 'Apparatus worn on the head that covers the eyes like a pair of goggles. It gives the user the \'feeling of being there\' by immersing them totally in the virtual reality experience.', aiExplanation: '虚拟现实头显 (VR)：一种头戴式显示器，能隔绝外部视觉，让用户沉浸在计算机生成的3D虚拟世界中。' },
  { id: getNextId(), chapterId: '3.1', term: 'Sensor', definition: 'Input device that reads physical data from its surroundings.', aiExplanation: '传感器：能感知物理环境（如温度、光线、压力）并将其转换为电信号的输入设备。' },

  // 3.2 Logic gates
  { id: getNextId(), chapterId: '3.2', term: 'Logic gates', definition: 'Electronic circuits which rely on \'on/off\' logic. The most common ones are NOT, AND, OR, NAND, NOR and XOR.', aiExplanation: '逻辑门：数字电路的基本构建块，根据输入信号执行基本的逻辑运算（如“与”、“或”、“非”）。' },
  { id: getNextId(), chapterId: '3.2', term: 'Logic circuit', definition: 'Formed from a combination of logic gates and designed to carry out a particular task. The output from a logic circuit will be 0 or 1.', aiExplanation: '逻辑电路：由多个逻辑门组合而成的复杂电路，用于执行特定的计算或控制任务。' },
  { id: getNextId(), chapterId: '3.2', term: 'Truth table', definition: 'A method of checking the output from a logic circuit. They use all the possible binary input combinations depending on the number of inputs; for example, two inputs have 2^2 (4) possible binary combinations.', aiExplanation: '真值表：列出逻辑电路所有可能输入及其对应输出结果的表格，是分析逻辑电路功能的工具。' },
  { id: getNextId(), chapterId: '3.2', term: 'Boolean algebra', definition: 'A form of algebra linked to logic circuits and based on TRUE and FALSE.', aiExplanation: '布尔代数：一种用于分析和简化逻辑电路的数学系统，变量的值仅为真（1）或假（0）。' },

  // 4.1 CPU Architecture
  { id: getNextId(), chapterId: '4.1', term: 'Von Neumann architecture', definition: 'Computer architecture which introduced the concept of the stored program in the 1940s.', aiExplanation: '冯·诺依曼架构：现代计算机的基础设计结构，核心思想是“存储程序”，即程序和数据都存储在同一个内存中。' },
  { id: getNextId(), chapterId: '4.1', term: 'Arithmetic logic unit (ALU)', definition: 'Component in the processor which carries out all arithmetic and logical operations.', aiExplanation: '算术逻辑单元 (ALU)：CPU的“大脑”，负责执行加减乘除等数学运算和与或非等逻辑判断。' },
  { id: getNextId(), chapterId: '4.1', term: 'Control unit', definition: 'Ensures synchronisation of data flow and programs throughout the computer by sending out control signals along the control bus.', aiExplanation: '控制器 (CU)：CPU的指挥中心，负责解码指令并指挥计算机各部件协调工作。' },
  { id: getNextId(), chapterId: '4.1', term: 'System clock', definition: 'Produces timing signals on the control bus to ensure synchronisation takes place.', aiExplanation: '系统时钟：发出有规律的脉冲信号，像节拍器一样协调计算机所有部件的同步工作。' },
  { id: getNextId(), chapterId: '4.1', term: 'Immediate access store (IAS)', definition: 'Holds all data and programs needed to be accessed by the control unit.', aiExplanation: '立即存取存储器：通常指内存或CPU缓存，用于存放CPU当前急需处理的数据和指令。' },
  { id: getNextId(), chapterId: '4.1', term: 'Accumulator', definition: 'Temporary general purpose register which stores numerical values at any part of a given operation.', aiExplanation: '累加器 (ACC)：一个特殊的寄存器，专门用来暂存ALU运算产生的中间结果。' },
  { id: getNextId(), chapterId: '4.1', term: 'Register', definition: 'Temporary component in the processor which can be general or specific in its use that holds data or instructions as part of the fetch-execute cycle.', aiExplanation: '寄存器：CPU内部速度极快的小容量存储单元，用于暂时存放正在处理的数据或指令。' },
  { id: getNextId(), chapterId: '4.1', term: 'Status register', definition: 'Used when an instruction requires some form of arithmetic or logical processing.', aiExplanation: '状态寄存器：记录运算结果状态的寄存器，例如结果是否为负、是否溢出或是否为零。' },
  { id: getNextId(), chapterId: '4.1', term: 'Flag', definition: 'Indicates the status of a bit in the status register, for example, N = 1 indicates the result of an addition gives a negative value.', aiExplanation: '标志位：状态寄存器中的一位，用于指示特定的状态，如进位标志或零标志。' },
  { id: getNextId(), chapterId: '4.1', term: 'Address bus', definition: 'Carries the addresses throughout the computer system.', aiExplanation: '地址总线：传输内存地址信号的通道，决定了CPU能访问的内存大小（单向传输）。' },
  { id: getNextId(), chapterId: '4.1', term: 'Data bus', definition: 'Allows data to be carried from processor to memory (and vice versa) or to and from input/output devices.', aiExplanation: '数据总线：在CPU、内存和I/O设备之间传输实际数据的通道（双向传输）。' },
  { id: getNextId(), chapterId: '4.1', term: 'Control bus', definition: 'Carries signals from control unit to all other computer components.', aiExplanation: '控制总线：传输控制信号（如读/写命令、中断信号）的通道，指挥各部件动作。' },
  { id: getNextId(), chapterId: '4.1', term: 'Unidirectional', definition: 'Used to describe a bus in which bits can travel in one direction only.', aiExplanation: '单向：指数据只能沿一个方向传输，如地址总线（只能从CPU发向内存）。' },
  { id: getNextId(), chapterId: '4.1', term: 'Bidirectional', definition: 'Used to describe a bus in which bits can travel in both directions.', aiExplanation: '双向：指数据可以在两个方向上传输，如数据总线。' },
  { id: getNextId(), chapterId: '4.1', term: 'Word', definition: 'Group of bits used by a computer to represent a single unit.', aiExplanation: '字 (Word)：CPU一次能处理的数据位数，如64位处理器的“字长”就是64位。' },
  { id: getNextId(), chapterId: '4.1', term: 'Clock cycle', definition: 'Clock speeds are measured in terms of GHz; this is the vibrational frequency of the clock which sends out pulses along the control bus - a 3.5 GHz clock cycle means 3.5 billion clock cycles a second.', aiExplanation: '时钟周期：计算机执行一个基本操作所需的时间单位，主频越高，周期越短，速度越快。' },
  { id: getNextId(), chapterId: '4.1', term: 'Overclocking', definition: 'Changing the clock speed of a system clock to a value higher than the factory/recommended setting.', aiExplanation: '超频：强行提高CPU或其他硬件的工作频率以提升性能，但会增加发热和不稳定性。' },
  { id: getNextId(), chapterId: '4.1', term: 'BIOS', definition: 'Basic input/output system.', aiExplanation: '基本输入输出系统 (BIOS)：固化在主板上的程序，负责开机硬件自检和引导操作系统。' },
  { id: getNextId(), chapterId: '4.1', term: 'Cache memory', definition: 'A high speed auxiliary memory which permits high speed data transfer and retrieval.', aiExplanation: '高速缓冲存储器：位于CPU内部的极速内存，存放CPU最常用的数据，以减少访问慢速主内存的次数。' },
  { id: getNextId(), chapterId: '4.1', term: 'Core', definition: 'A unit made up of ALU, control unit and registers which is part of a CPU. A CPU may contain a number of cores.', aiExplanation: '核心：CPU内的独立处理单元，包含完整的运算和控制逻辑。多核CPU就像多个人一起工作。' },
  { id: getNextId(), chapterId: '4.1', term: 'Dual core', definition: 'A CPU containing two cores.', aiExplanation: '双核：拥有两个独立核心的CPU。' },
  { id: getNextId(), chapterId: '4.1', term: 'Quad core', definition: 'A CPU containing four cores.', aiExplanation: '四核：拥有四个独立核心的CPU。' },
  { id: getNextId(), chapterId: '4.1', term: 'Port', definition: 'External connection to a computer which allows it to communicate with various peripheral devices. A number of different port technologies exist.', aiExplanation: '接口/端口：电脑与外部设备连接的插口，如USB口、HDMI口。' },
  { id: getNextId(), chapterId: '4.1', term: 'Universal Serial Bus (USB)', definition: 'A type of port connecting devices to a computer.', aiExplanation: '通用串行总线 (USB)：最常用的外设连接接口，支持热插拔，可连接鼠标、键盘、U盘等。' },
  { id: getNextId(), chapterId: '4.1', term: 'Asynchronous serial data transmission', definition: 'Serial refers to a single wire being used to transmit bits of data one after the other. Asynchronous refers to a sender using its own clock/timer device rather sharing the same clock/timer with the recipient device.', aiExplanation: '异步串行数据传输：一种通信方式，数据按位顺序发送，发送方和接收方不需要时钟同步，而是通过起始位和停止位来识别数据。' },
  { id: getNextId(), chapterId: '4.1', term: 'High-definition multimedia interface (HDMI)', definition: 'Type of port connecting devices to a computer.', aiExplanation: '高清多媒体接口 (HDMI)：用于同时传输高清视频和音频信号的数字化接口。' },
  { id: getNextId(), chapterId: '4.1', term: 'Video Graphics Array (VGA)', definition: 'Type of port connecting devices to a computer.', aiExplanation: 'VGA接口：一种老式的模拟视频信号传输接口，常用于旧显示器投影仪。' },
  { id: getNextId(), chapterId: '4.1', term: 'High-bandwidth digital copy protection (HDCP)', definition: 'Part of HDMI technology which reduces risk of piracy of software and multimedia.', aiExplanation: '高带宽数字内容保护 (HDCP)：HDMI接口中用于防止高清内容被非法录制和复制的加密技术。' },
  { id: getNextId(), chapterId: '4.1', term: 'Fetch-execute cycle', definition: 'A cycle in which instructions and data are fetched from memory and then decoded and finally executed.', aiExplanation: '取指-执行周期：CPU工作的基本循环流程——从内存取出指令、分析指令含义、执行指令。' },
  { id: getNextId(), chapterId: '4.1', term: 'Program counter (PC)', definition: 'A register used in a computer to store the address of the instruction which is currently being executed.', aiExplanation: '程序计数器 (PC)：存放下一条将要执行的指令在内存中的地址，控制程序执行顺序。' },
  { id: getNextId(), chapterId: '4.1', term: 'Current instruction register', definition: 'A register used to contain the instruction which is currently being executed or decoded.', aiExplanation: '当前指令寄存器 (CIR/IR)：存放当前正在被CPU解码和执行的那条指令内容。' },
  { id: getNextId(), chapterId: '4.1', term: 'Register Transfer Notation (RTN)', definition: 'Short hand notation to show movement of data and instructions in a processor, can be used to represent the operation of the fetch-execute cycle.', aiExplanation: '寄存器传输级语言 (RTN)：一种描述CPU内部数据如何在寄存器之间流动的数学符号表示法。' },
  { id: getNextId(), chapterId: '4.1', term: 'Interrupt', definition: 'Signal sent from a device or software to a processor requesting its attention; the processor suspends all operations until the interrupt has been serviced.', aiExplanation: '中断：硬件或软件发出的紧急信号，打断CPU当前工作，请求CPU优先处理突发事件（如按键、打印机缺纸）。' },
  { id: getNextId(), chapterId: '4.1', term: 'Interrupt priority', definition: 'All interrupts are given a priority so that the processor knows which need to be serviced first and which interrupts are to be dealt with quickly.', aiExplanation: '中断优先级：给不同类型的中断设定等级，确保CPU优先处理最紧急的任务。' },
  { id: getNextId(), chapterId: '4.1', term: 'Interrupt service routine (ISR)', definition: 'Software which handles interrupt requests (such as \'printer out of paper\') and sends the request to the CPU for processing.', aiExplanation: '中断服务程序 (ISR)：当发生中断时，CPU暂停当前任务去执行的一段专门处理该中断的程序代码。' },

  // 4.2 Assembly language
  { id: getNextId(), chapterId: '4.2', term: 'Machine code', definition: 'The programming language that the CPU uses.', aiExplanation: '机器码：CPU能直接“看懂”和执行的语言，完全由0和1组成的代码。' },
  { id: getNextId(), chapterId: '4.2', term: 'Instruction', definition: 'A single operation performed by a CPU.', aiExplanation: '指令：告诉CPU做某一个具体动作（如加法、移动数据）的命令。' },
  { id: getNextId(), chapterId: '4.2', term: 'Assembly language', definition: 'A low-level chip/machine specific programming language that uses mnemonics.', aiExplanation: '汇编语言：一种低级编程语言，用人类可读的助记符（如ADD、MOV）代替难记的机器码。' },
  { id: getNextId(), chapterId: '4.2', term: 'Opcode', definition: 'Short for operation code, the part of a machine code instruction that identifies the action the CPU will perform.', aiExplanation: '操作码：指令中告诉CPU“做什么”（如加、减、跳转）的部分。' },
  { id: getNextId(), chapterId: '4.2', term: 'Operand', definition: 'The part of a machine code instruction that identifies the data to be used by the CPU.', aiExplanation: '操作数：指令中告诉CPU“对谁做”（如数据本身或数据的内存地址）的部分。' },
  { id: getNextId(), chapterId: '4.2', term: 'Source code', definition: 'A computer program before translation into machine code.', aiExplanation: '源代码：程序员用编程语言编写的原始程序文本。' },
  { id: getNextId(), chapterId: '4.2', term: 'Assembler', definition: 'A computer program that translates programming code written in assembly language into machine code. Assemblers can be one pass or two pass.', aiExplanation: '汇编器：将汇编语言代码翻译成机器码的翻译软件。' },
  { id: getNextId(), chapterId: '4.2', term: 'Instruction set', definition: 'The complete set of machine code instructions used by a CPU.', aiExplanation: '指令集：某款CPU所能识别和执行的所有指令的集合。' },
  { id: getNextId(), chapterId: '4.2', term: 'Object code', definition: 'A computer program after translation into machine code.', aiExplanation: '目标代码：源代码经过编译或汇编后生成的机器语言代码。' },
  { id: getNextId(), chapterId: '4.2', term: 'Addressing modes', definition: 'Different methods of using the operand part of a machine code instruction as a memory address.', aiExplanation: '寻址方式：指令中指定数据位置的不同方法（如直接给出数据，或给出数据的地址）。' },
  { id: getNextId(), chapterId: '4.2', term: 'Absolute addressing', definition: 'Mode of addressing in which the contents of the memory location in the operand are used.', aiExplanation: '绝对寻址：指令中直接给出数据在内存中的确切地址。' },
  { id: getNextId(), chapterId: '4.2', term: 'Direct addressing', definition: 'Mode of addressing in which the contents of the memory location in the operand are used, which is the same as absolute addressing.', aiExplanation: '直接寻址：同绝对寻址，直接给出数据的内存地址。' },
  { id: getNextId(), chapterId: '4.2', term: 'Indirect addressing', definition: 'Mode of addressing in which the contents of the memory location in the operand are used to give the address of the data.', aiExplanation: '间接寻址：指令给出一个地址，该地址里存的才是数据的真实地址（像寻宝游戏的线索）。' },
  { id: getNextId(), chapterId: '4.2', term: 'Indexed addressing', definition: 'Mode of addressing in which the contents of the memory location found by adding the contents of the index register (IR) to the address of the memory location in the operand are used.', aiExplanation: '变址寻址：最终地址由指令中的基准地址加上变址寄存器中的偏移量计算得出，常用于访问数组。' },
  { id: getNextId(), chapterId: '4.2', term: 'Immediate addressing', definition: 'Mode of addressing in which the value of the operand only is used.', aiExplanation: '立即寻址：指令中直接包含要操作的数据本身，而不是数据的地址。' },
  { id: getNextId(), chapterId: '4.2', term: 'Relative addressing', definition: 'Mode of addressing in which the memory address used is the current memory address added to the operand.', aiExplanation: '相对寻址：以当前指令地址为基准，加上一个偏移量来确定目标地址，常用于程序跳转。' },
  { id: getNextId(), chapterId: '4.2', term: 'Symbolic addressing', definition: 'Mode of addressing used in assembly language programming, where a label is used instead of a value.', aiExplanation: '符号寻址：在汇编代码中用有意义的标签（Label）代替具体的内存地址。' },

  // 4.3 Bit manipulation
  { id: getNextId(), chapterId: '4.3', term: 'Shift', definition: 'Moving the bits stored in a register a given number of places within the register; there are different types of shift.', aiExplanation: '移位：将寄存器中的二进制位整体向左或向右移动的操作。' },
  { id: getNextId(), chapterId: '4.3', term: 'Logical shift', definition: 'Bits shifted out of the register are replaced with zeros.', aiExplanation: '逻辑移位：移位后空出的位置直接补0，适用于无符号数。' },
  { id: getNextId(), chapterId: '4.3', term: 'Arithmetic shift', definition: 'The sign of the number is preserved.', aiExplanation: '算术移位：移位时保留符号位不变，用于有符号数的乘除运算。' },
  { id: getNextId(), chapterId: '4.3', term: 'Cyclic shift', definition: 'No bits are lost, bits shifted out of one end of the register are introduced at the other end of the register.', aiExplanation: '循环移位：移出的位会补回到另一端，像环一样转动，不会丢失信息。' },
  { id: getNextId(), chapterId: '4.3', term: 'Left shift', definition: 'Bits are shifted to the left.', aiExplanation: '左移：所有位向左移动，通常相当于乘以2。' },
  { id: getNextId(), chapterId: '4.3', term: 'Right shift', definition: 'Bits are shifted to the right.', aiExplanation: '右移：所有位向右移动，通常相当于除以2。' },
  { id: getNextId(), chapterId: '4.3', term: 'Monitor', definition: 'To automatically take readings from a device.', aiExplanation: '监测：系统自动读取传感器或设备状态数据的过程。' },
  { id: getNextId(), chapterId: '4.3', term: 'Control', definition: 'To automatically take readings from a device, then use the data from those readings to adjust the device.', aiExplanation: '控制：监测数据并根据数据主动调节设备运行状态的过程（如恒温器）。' },
  { id: getNextId(), chapterId: '4.3', term: 'Mask', definition: 'A number that is used with the logical operators AND, OR or XOR to identify, remove or set a single bit or group of bits in an address or register.', aiExplanation: '掩码：一串用于筛选、屏蔽或设置特定二进制位的数字，常配合逻辑运算使用。' },

  // 5.1 Operating systems
  { id: getNextId(), chapterId: '5.1', term: 'CMOS', definition: 'Complementary metal-oxide semiconductor.', aiExplanation: 'CMOS：一种用于保存BIOS设置和系统时间的低功耗芯片，断电需电池供电。' },
  { id: getNextId(), chapterId: '5.1', term: 'Operating system', definition: 'Software that provides an environment in which applications can run and provides an interface between hardware and human operators.', aiExplanation: '操作系统 (OS)：管理电脑硬件与软件资源的系统软件，如Windows、macOS，是用户与电脑沟通的桥梁。' },
  { id: getNextId(), chapterId: '5.1', term: 'HCI', definition: 'Human-computer interface.', aiExplanation: '人机交互接口 (HCI)：人与计算机系统之间进行信息交换和控制的界面。' },
  { id: getNextId(), chapterId: '5.1', term: 'GUI', definition: 'Graphical user interface.', aiExplanation: '图形用户界面 (GUI)：使用图标、窗口和菜单等图形元素来操作电脑的界面，直观易用。' },
  { id: getNextId(), chapterId: '5.1', term: 'CLI', definition: 'Command line interface.', aiExplanation: '命令行界面 (CLI)：通过输入文本命令来操作电脑的界面，专业且高效，如DOS或Linux终端。' },
  { id: getNextId(), chapterId: '5.1', term: 'Icon', definition: 'Small picture or symbol used to represent, for example, an application on a screen.', aiExplanation: '图标：代表程序、文件或功能的微小图形符号。' },
  { id: getNextId(), chapterId: '5.1', term: 'WIMP', definition: 'Windows, icons, menu and pointing device.', aiExplanation: 'WIMP：传统桌面操作系统的四大交互元素——窗口、图标、菜单、指针（鼠标）。' },
  { id: getNextId(), chapterId: '5.1', term: 'Post-WIMP', definition: 'Interfaces that go beyond WIMP and use touch screen technology rather than a pointing device.', aiExplanation: '后WIMP时代：指触屏、手势、语音等新一代交互方式，不再依赖鼠标和菜单。' },
  { id: getNextId(), chapterId: '5.1', term: 'Pinching and rotating', definition: 'Actions by fingers on a touch screen to carry out tasks such as move, enlarge, reduce, and so on.', aiExplanation: '捏合与旋转：触屏上常用的多点触控手势，用于缩放和旋转图片或地图。' },
  { id: getNextId(), chapterId: '5.1', term: 'Memory management', definition: 'Part of the operating system that controls the main memory.', aiExplanation: '内存管理：操作系统的核心功能之一，负责分配和回收内存空间，确保程序正常运行。' },
  { id: getNextId(), chapterId: '5.1', term: 'Memory optimisation', definition: 'Function of memory management that determines how memory is allocated and deallocated.', aiExplanation: '内存优化：提高内存使用效率的策略，防止内存浪费。' },
  { id: getNextId(), chapterId: '5.1', term: 'Memory organisation', definition: 'Function of memory management that determines how much memory is allocated to an application.', aiExplanation: '内存组织：决定每个程序在内存中占用多大空间以及在什么位置。' },
  { id: getNextId(), chapterId: '5.1', term: 'Security management', definition: 'Part of the operating system that ensures the integrity, confidentiality and availability of data.', aiExplanation: '安全管理：操作系统负责保护数据不被非法访问、篡改或丢失的功能。' },
  { id: getNextId(), chapterId: '5.1', term: 'Contiguous', definition: 'Items next to each other.', aiExplanation: '连续：指数据存储在物理上相邻的内存或磁盘块中。' },
  { id: getNextId(), chapterId: '5.1', term: 'Virtual memory systems', definition: 'Memory management (part of OS) that makes use of hardware and software to enable a computer to compensate for shortage of actual physical memory.', aiExplanation: '虚拟内存：当物理内存不足时，利用硬盘空间模拟内存的技术，让电脑能运行更多或更大的程序。' },
  { id: getNextId(), chapterId: '5.1', term: 'Memory protection', definition: 'Function of memory management that ensures two competing applications cannot use same memory locations at the same time.', aiExplanation: '内存保护：防止一个程序意外修改另一个程序或操作系统的内存数据，保证系统稳定。' },
  { id: getNextId(), chapterId: '5.1', term: 'Process management', definition: 'Part of the operating system that involves allocation of resources and permits the sharing and exchange of data.', aiExplanation: '进程管理：操作系统负责调度CPU时间，管理运行中的程序（进程）及其资源分配。' },
  { id: getNextId(), chapterId: '5.1', term: 'Program library', definition: 'A library on a computer where programs and routines are stored which can be freely accessed by other software developers for use in their own programs.', aiExplanation: '程序库：包含预先写好的代码片段的集合，程序员可以直接调用以节省开发时间。' },
  { id: getNextId(), chapterId: '5.1', term: 'Library program', definition: 'A program stored in a library for future use by other programmers.', aiExplanation: '库程序：存储在库中供调用的具体功能模块。' },
  { id: getNextId(), chapterId: '5.1', term: 'Hardware management', definition: 'Part of the operating system that controls all input/output devices connected to a computer (made up of sub-management systems such as printer management, secondary storage management, and so on).' },
  { id: getNextId(), chapterId: '5.1', term: 'Device driver', definition: 'Software that communicates with the operating system and translates data into a format understood by the device.', aiExplanation: '驱动程序：告诉操作系统如何与特定硬件（如显卡、打印机）通信的软件。' },
  { id: getNextId(), chapterId: '5.1', term: 'Utility program', definition: 'Parts of the operating system which carry out certain functions, such as virus checking, defragmentation or hard disk formatting.', aiExplanation: '实用程序：用于维护系统、优化性能或执行特定辅助任务的小软件（如磁盘清理、杀毒）。' },
  { id: getNextId(), chapterId: '5.1', term: 'Disk formatter', definition: 'Utility that prepares a disk to allow data/files to be stored and retrieved.', aiExplanation: '磁盘格式化工具：将磁盘划分为磁道和扇区并建立文件系统，以便存储数据的工具。' },
  { id: getNextId(), chapterId: '5.1', term: 'Bad sector', definition: 'A faulty sector on an HDD which can be soft or hard.', aiExplanation: '坏道：硬盘上物理损坏或逻辑错误无法存储数据的区域。' },
  { id: getNextId(), chapterId: '5.1', term: 'Antivirus software', definition: 'Software that quarantines and deletes files or programs infected by a virus (or other malware). It can be run in the background or initiated by the user.', aiExplanation: '杀毒软件：用于侦测、隔离和清除计算机病毒及恶意软件的安全程序。' },
  { id: getNextId(), chapterId: '5.1', term: 'Heuristic checking', definition: 'Checking of software for behaviour that could indicate a possible virus.', aiExplanation: '启发式扫描：通过分析程序行为而非仅靠病毒库特征码来发现未知病毒的技术。' },
  { id: getNextId(), chapterId: '5.1', term: 'Quarantine', definition: 'File or program identified as being infected by a virus which has been isolated by antivirus software before it is deleted at a later stage.', aiExplanation: '隔离区：杀毒软件存放可疑文件的安全区域，防止病毒扩散，等待进一步处理。' },
  { id: getNextId(), chapterId: '5.1', term: 'False positive', definition: 'A file or program identified by a virus checker as being infected but the user knows this cannot be correct.', aiExplanation: '误报：杀毒软件错误地将正常无害的文件报告为病毒。' },
  { id: getNextId(), chapterId: '5.1', term: 'Disk defragmenter', definition: 'Utility that reorganises the sectors on a hard disk so that files can be stored in contiguous data blocks.', aiExplanation: '磁盘碎片整理：将分散存储的文件碎片重新排列到连续区域，提高机械硬盘读写速度。' },
  { id: getNextId(), chapterId: '5.1', term: 'Disk content analysis software', definition: 'Utility that checks disk drives for empty space and disk usage by reviewing files and folders.', aiExplanation: '磁盘分析工具：扫描磁盘使用情况，展示哪些文件占用了空间的工具。' },
  { id: getNextId(), chapterId: '5.1', term: 'Disk compression', definition: 'Software that compresses data before storage on an HDD.', aiExplanation: '磁盘压缩：自动压缩存储在磁盘上的文件以节省空间的技术。' },
  { id: getNextId(), chapterId: '5.1', term: 'Back-up utility', definition: 'Software that makes copies of files on another portable storage device.', aiExplanation: '备份工具：用于创建数据副本并存储到安全位置以防丢失的软件。' },
  { id: getNextId(), chapterId: '5.1', term: 'Library routine', definition: 'A tested and ready-to-use routine available in the development system of a programming language that can be incorporated into a program.', aiExplanation: '库例程：编程语言自带的、经过测试的标准函数（如数学计算、输入输出），可直接使用。' },
  { id: getNextId(), chapterId: '5.1', term: 'Dynamic link file (DLL)', definition: 'A library routine that can be linked to another program only at the run time stage.', aiExplanation: '动态链接库 (DLL)：程序运行时才调用的共享代码文件，多个程序可以共用同一个DLL以节省内存。' },

  // 5.2 Language translators
  { id: getNextId(), chapterId: '5.2', term: 'Translator', definition: 'The systems software used to translate a source program written in any language other than machine code.', aiExplanation: '翻译器：将程序员写的高级语言代码转换为计算机能执行的机器码的系统软件统称。' },
  { id: getNextId(), chapterId: '5.2', term: 'Compiler', definition: 'A computer program that translates a source program written in a high-level language to machine code or p-code, object code.', aiExplanation: '编译器：将整个源代码一次性翻译成可执行文件（目标代码）的程序，执行速度快。' },
  { id: getNextId(), chapterId: '5.2', term: 'Integrated development environment (IDE)', definition: 'A suite of programs used to write and test a computer program written in a high-level programming language.', aiExplanation: '集成开发环境 (IDE)：集成了代码编辑、编译、调试等功能的编程软件套装，如Visual Studio。' },
  { id: getNextId(), chapterId: '5.2', term: 'Syntax error', definition: 'An error in the grammar of a source program.', aiExplanation: '语法错误：代码不符合编程语言的语法规则（如拼写错误、漏掉分号），导致无法编译。' },
  { id: getNextId(), chapterId: '5.2', term: 'Logic error', definition: 'An error in the logic of a program.', aiExplanation: '逻辑错误：代码语法正确能运行，但程序执行思路不对，导致结果不符合预期（如死循环、算错数）。' },
  { id: getNextId(), chapterId: '5.2', term: 'Debugging', definition: 'The process of finding logic errors in a computer program by running or tracing the program.', aiExplanation: '调试 (Debug)：查找并修复程序错误的过程。' },
  { id: getNextId(), chapterId: '5.2', term: 'Interpreter', definition: 'A computer program that analyses and executes a program written in a high-level language line by line.', aiExplanation: '解释器：读一行代码就翻译执行一行，不生成独立可执行文件，便于调试但运行稍慢（如Python）。' },
  { id: getNextId(), chapterId: '5.2', term: 'Prettyprinting', definition: 'The practice of displaying or printing well set out and formatted source code, making it easier to read and understand.', aiExplanation: '格式化打印：自动调整代码缩进、颜色和格式，使其更易读美观。' },
  { id: getNextId(), chapterId: '5.2', term: 'Single stepping', definition: 'The practice of running a program one line/instruction at a time.', aiExplanation: '单步执行：调试时让程序一次只执行一行代码，以便观察每一步的变化。' },
  { id: getNextId(), chapterId: '5.2', term: 'Breakpoint', definition: 'A deliberate pause in the execution of a program during testing so that the contents of variables, registers, and so on can be inspected to aid debugging.', aiExplanation: '断点：在代码中设置的一个标记，程序运行到这里会自动暂停，方便程序员检查状态。' },
  { id: getNextId(), chapterId: '5.2', term: 'Report window', definition: 'A separate window in the run-time environment of the IDE that shows the contents of variables during the execution of a program.', aiExplanation: '监视窗口：调试时用于实时显示变量值和系统状态的窗口。' },

  // 6.1 Data Security
  { id: getNextId(), chapterId: '6.1', term: 'Data privacy', definition: 'The privacy of personal information, or other information stored on a computer, that should not be accessed by unauthorised parties.', aiExplanation: '数据隐私：确保个人或敏感数据不被未授权人员查看或使用的权利。' },
  { id: getNextId(), chapterId: '6.1', term: 'Data protection laws', definition: 'Laws which govern how data should be kept private and secure.', aiExplanation: '数据保护法：法律法规，规定组织必须如何收集、存储和保护个人数据（如GDPR）。' },
  { id: getNextId(), chapterId: '6.1', term: 'Data security', definition: 'Methods taken to prevent unauthorised access to data and to recover data if lost or corrupted.', aiExplanation: '数据安全：保护数字信息不受非法访问、破坏或丢失的技术和措施。' },
  { id: getNextId(), chapterId: '6.1', term: 'Malware', definition: 'Malicious software that seeks to damage or gain unauthorised access to a computer system.', aiExplanation: '恶意软件：任何以危害计算机系统为目的的软件统称，如病毒、木马、勒索软件。' },
  { id: getNextId(), chapterId: '6.1', term: 'Firewall', definition: 'Software or hardware that sits between a computer and external network that monitors and filters all incoming and outgoing activities.', aiExplanation: '防火墙：一道网络安全屏障，监控进出网络的数据流，阻挡潜在攻击。' },
  { id: getNextId(), chapterId: '6.1', term: 'Anti-spyware software', definition: 'Software that detects and removes spyware programs installed illegally on a user\'s computer system.', aiExplanation: '反间谍软件：专门用于发现和删除试图窃取用户信息的间谍程序的软件。' },
  { id: getNextId(), chapterId: '6.1', term: 'Encryption', definition: 'The use of encryption keys to make data meaningless without the correct decryption key.', aiExplanation: '加密：将数据转换成乱码，只有拥有解密密钥的人才能还原阅读。' },
  { id: getNextId(), chapterId: '6.1', term: 'Biometrics', definition: 'Use of unique human characteristics to identify a user (such as fingerprints or face recognition).', aiExplanation: '生物特征识别：利用指纹、人脸、虹膜等独一无二的人体特征进行身份认证的技术。' },
  { id: getNextId(), chapterId: '6.1', term: 'Hacking', definition: 'Illegal access to a computer system without the owner\'s permission.', aiExplanation: '黑客攻击：未经授权擅自进入或操纵计算机系统的行为。' },
  { id: getNextId(), chapterId: '6.1', term: 'Malicious hacking', definition: 'Hacking done with the sole intent of causing harm to a computer system or user (for example, deletion of files or use of private data to the hacker\'s advantage).', aiExplanation: '恶意黑客：出于破坏、盗窃或勒索目的进行的黑客行为（Black Hat）。' },
  { id: getNextId(), chapterId: '6.1', term: 'User account', definition: 'An agreement that allows an individual to use a computer or network server, often requiring a user name and password.', aiExplanation: '用户账户：用户在系统中的身份标识，通常包含用户名和密码，用于控制权限。' },
  { id: getNextId(), chapterId: '6.1', term: 'Authentication', definition: 'A way of proving somebody or something is who or what they claim to be.', aiExplanation: '身份验证：确认用户身份真实性的过程（如输入密码、刷脸）。' },
  { id: getNextId(), chapterId: '6.1', term: 'Access rights (data security)', definition: 'Use of access levels to ensure only authorised users can gain access to certain data.', aiExplanation: '访问权限：设定用户能看什么、改什么的规则，防止越权操作。' },
  { id: getNextId(), chapterId: '6.1', term: 'Ethical hacking', definition: 'Hacking used to test the security and vulnerability of a computer system. The hacking is carried out with the permission of the computer system owner, for example, to help a company identify risks associated with malicious hacking of their computer systems.', aiExplanation: '道德黑客（白帽）：经授权攻击系统以寻找安全漏洞，帮助修复和提升安全性的专家。' },
  { id: getNextId(), chapterId: '6.1', term: 'Phishing', definition: 'Legitimate-looking emails designed to trick a recipient into giving their personal data to the sender of the email.', aiExplanation: '网络钓鱼：伪装成银行或官方机构发送诈骗邮件，诱骗受害者提供密码或敏感信息。' },
  { id: getNextId(), chapterId: '6.1', term: 'Pharming', definition: 'Redirecting a user to a fake website in order to illegally obtain personal data about the user.', aiExplanation: '嫁接攻击/域名欺骗：将用户访问的正确网址悄悄重定向到假冒网站，以窃取信息。' },
  { id: getNextId(), chapterId: '6.1', term: 'DNS cache poisoning', definition: 'Altering IP addresses on a DNS server by a \'pharmer\' or hacker with the intention of redirecting a user to their fake website.', aiExplanation: 'DNS缓存投毒：篡改DNS服务器记录，让用户输入正确网址却被带到黑客服务器。' },

  // 6.2 Data Integrity
  { id: getNextId(), chapterId: '6.2', term: 'Data integrity', definition: 'The accuracy, completeness and consistency of data.', aiExplanation: '数据完整性：确保数据在传输和存储过程中保持准确、完整、未被篡改的状态。' },
  { id: getNextId(), chapterId: '6.2', term: 'Validation', definition: 'Method used to ensure entered data is reasonable and meets certain input criteria.', aiExplanation: '数据验证：在数据输入系统前检查其是否符合规则（如检查年龄是否为数字、日期格式是否正确）。' },
  { id: getNextId(), chapterId: '6.2', term: 'Verification', definition: 'Method used to ensure data is correct by using double entry or visual checks.', aiExplanation: '数据校验：确认输入的数据与原始来源一致（如双次输入密码、人工核对）。' },
  { id: getNextId(), chapterId: '6.2', term: 'Check digit', definition: 'Additional digit appended to a number to check if entered data is error free.', aiExplanation: '校验位：加在数字代码末尾的一位额外数字，通过算法验证前面的数字是否输入正确（如身份证号最后一位）。' },
  { id: getNextId(), chapterId: '6.2', term: 'Modulo-11', definition: 'Method used to calculate a check digit based on modulus division by 11.', aiExplanation: '模11算法：一种常用的计算校验位的数学方法，广泛用于ISBN书号。' },
  { id: getNextId(), chapterId: '6.2', term: 'Checksum', definition: 'Verification method used to check if data transferred has been altered or corrupted, calculated from the block of data to be sent.', aiExplanation: '校验和：对数据块内容计算出的一个数值，接收方通过比对该数值来判断数据传输是否出错。' },
  { id: getNextId(), chapterId: '6.2', term: 'Parity check', definition: 'Method used to check if data has been transferred correctly that uses even or odd parity.', aiExplanation: '奇偶校验：一种简单的数据检错机制，通过检查1的个数是奇数还是偶数来发现错误。' },
  { id: getNextId(), chapterId: '6.2', term: 'Parity bit', definition: 'An extra bit found at the end of a byte that is set to 1 if the parity of the byte needs to change to agree with sender/ receiver parity protocol.', aiExplanation: '奇偶校验位：为了满足奇偶性要求而添加在数据末尾的一位二进制数（0或1）。' },
  { id: getNextId(), chapterId: '6.2', term: 'Odd parity', definition: 'Binary number with an odd number of 1-bits.', aiExplanation: '奇校验：确保数据中包含奇数个“1”，如果不满足则通过校验位调整。' },
  { id: getNextId(), chapterId: '6.2', term: 'Even parity', definition: 'Binary number with an even number of 1-bits.', aiExplanation: '偶校验：确保数据中包含偶数个“1”。' },
  { id: getNextId(), chapterId: '6.2', term: 'Parity block', definition: 'Horizontal and vertical parity check on a block of data being transferred.', aiExplanation: '奇偶校验块：对数据块同时进行横向和纵向的奇偶校验，能发现更多错误甚至纠错。' },

  // 7.1 Legal, moral, ethical and cultural implications
  { id: getNextId(), chapterId: '7.1', term: 'Legal', definition: 'Relating to, or permissible by, law.', aiExplanation: '法律：受国家法律法规约束的，违规会导致法律制裁。' },
  { id: getNextId(), chapterId: '7.1', term: 'Morality', definition: 'An understanding of the difference between right and wrong, often founded in personal beliefs.', aiExplanation: '道德：基于个人信仰或社会观念对是非对错的判断，属内在约束。' },
  { id: getNextId(), chapterId: '7.1', term: 'Ethics', definition: 'Moral principles governing an individual\'s or organisation\'s behaviour, such as a code of conduct.', aiExplanation: '伦理：特定职业或团体遵守的行为准则和规范（如计算机职业伦理）。' },
  { id: getNextId(), chapterId: '7.1', term: 'Culture', definition: 'The attitudes, values and practices shared by a group of people/society.', aiExplanation: '文化：一个群体共同的生活方式、价值观和习俗，影响技术的使用方式。' },
  { id: getNextId(), chapterId: '7.1', term: 'Intellectual property rights', definition: 'Rules governing an individual\'s ownership of their own creations or ideas, prohibiting the copying of, for example, software without the owner\'s permission.', aiExplanation: '知识产权：法律赋予创作者对其智力成果（如软件、文章、发明）的专有权。' },
  { id: getNextId(), chapterId: '7.1', term: 'Privacy', definition: 'The right to keep personal information and data secret and for it to not be unwillingly accessed or shared through, for example, hacking.', aiExplanation: '隐私权：个人控制自己信息不被外界知晓或侵犯的权利。' },
  { id: getNextId(), chapterId: '7.1', term: 'Plagiarism', definition: 'The act of taking another person\'s work and claiming it as one\'s own.', aiExplanation: '剽窃/抄袭：窃取他人的作品或思想并当作自己的成果发表，是不道德行为。' },
  { id: getNextId(), chapterId: '7.1', term: 'BCS', definition: 'British Computer Society.', aiExplanation: '英国计算机学会 (BCS)：英国IT行业的专业机构，制定行业标准和职业道德规范。' },
  { id: getNextId(), chapterId: '7.1', term: 'IEEE', definition: 'Institute of Electrical and Electronics Engineers.', aiExplanation: '电气电子工程师学会 (IEEE)：世界上最大的技术专业组织，制定了许多计算机和通信标准（如Wi-Fi标准）。' },
  { id: getNextId(), chapterId: '7.1', term: 'ACM', definition: 'Association for Computing Machinery.', aiExplanation: '美国计算机协会 (ACM)：世界上历史最悠久、最大的计算机教育和科研机构。' },

  // 7.2 Copyright issues
  { id: getNextId(), chapterId: '7.2', term: 'Piracy', definition: 'The practice of using or making illegal copies of, for example, software.', aiExplanation: '盗版：未经授权非法复制、分发或使用受版权保护的软件或媒体内容。' },
  { id: getNextId(), chapterId: '7.2', term: 'Product key', definition: 'Security method used in software to protect against illegal copies or use.', aiExplanation: '产品密钥/序列号：一串用于验证软件正版授权的代码，防止盗版安装。' },
  { id: getNextId(), chapterId: '7.2', term: 'Digital rights management (DRM)', definition: 'Used to control the access to copyrighted material.', aiExplanation: '数字版权管理 (DRM)：通过技术手段限制数字内容被复制或非法使用（如限制电子书只能在特定设备阅读）。' },
  { id: getNextId(), chapterId: '7.2', term: 'Free Software Foundation', definition: 'Organisation promoting the free distribution of software, giving users the freedom to run, copy, change or adapt the coding as needed.', aiExplanation: '自由软件基金会 (FSF)：倡导用户有权自由运行、复制、研究和修改软件的非营利组织。' },
  { id: getNextId(), chapterId: '7.2', term: 'Open Source Initiative', definition: 'Organisation offering the same freedoms as the Free Software Foundation, but with more of a focus on the practical consequences of the four shared rules, such as more collaborative software development.', aiExplanation: '开源促进会 (OSI)：推动开源软件发展的组织，强调代码公开和协作开发。' },
  { id: getNextId(), chapterId: '7.2', term: 'Freeware', definition: 'Software that can be downloaded free of charge; however, it is covered by the usual copyright laws and cannot be modified; nor can the code be used for another purpose.', aiExplanation: '免费软件：可以免费下载使用的软件，但用户通常没有源代码，也不能修改或以此牟利（如微信）。' },
  { id: getNextId(), chapterId: '7.2', term: 'Shareware', definition: 'Software that is free of charge initially (free trial period). The full version of the software can only be downloaded once the full fee for the software has been paid.', aiExplanation: '共享软件：先试后买的软件，提供免费试用期，期满后需付费才能继续使用完整功能。' },

  // 7.3 Artificial Intelligence
  { id: getNextId(), chapterId: '7.3', term: 'Artificial intelligence (AI)', definition: 'Machine or application which carries out a task that requires some degree of intelligence when carried out by a human counterpart.', aiExplanation: '人工智能 (AI)：让机器模拟人类智能来执行任务（如识别图像、理解语言、决策）的技术。' },

  // 8.1 Database concepts
  { id: getNextId(), chapterId: '8.1', term: 'Database', definition: 'A structured collection of items of data that can be accessed by different applications programs.', aiExplanation: '数据库：有组织地存储数据的集合，方便计算机系统高效地检索和管理。' },
  { id: getNextId(), chapterId: '8.1', term: 'Relational database', definition: 'A database where the data items are linked by internal pointers.', aiExplanation: '关系型数据库：基于表（Table）结构存储数据的数据库，表与表之间通过公共字段建立关联。' },
  { id: getNextId(), chapterId: '8.1', term: 'Field', definition: 'A column in a table in a database.', aiExplanation: '字段：数据库表中的一列，代表数据的一个属性（如“姓名”或“年龄”）。' },
  { id: getNextId(), chapterId: '8.1', term: 'Tuple', definition: 'One instance of an entity, which is represented by a row in a table.', aiExplanation: '元组：数据库表中的一行，代表一条完整的记录（如某一个人的完整信息）。' },
  { id: getNextId(), chapterId: '8.1', term: 'Entity', definition: 'Anything that can have data stored about it, for example, a person, place, event, thing.', aiExplanation: '实体：现实世界中可以被描述和存储信息的对象（如“学生”、“订单”）。' },
  { id: getNextId(), chapterId: '8.1', term: 'Attribute (database)', definition: 'An individual data item stored for an entity, for example, for a person, attributes could include name, address, date of birth.', aiExplanation: '属性：实体的特征，对应数据库表中的字段。' },
  { id: getNextId(), chapterId: '8.1', term: 'Candidate key', definition: 'An attribute or smallest set of attributes in a table where no tuple has the same value.', aiExplanation: '候选键：能够唯一标识一条记录的字段（或字段组合），可能有多个，其中一个会被选为主键。' },
  { id: getNextId(), chapterId: '8.1', term: 'Primary key', definition: 'A unique identifier for a table. It is a special case of a candidate key.', aiExplanation: '主键：被选定用于唯一标识表中每一行记录的字段，不能重复，不能为空。' },
  { id: getNextId(), chapterId: '8.1', term: 'Secondary key', definition: 'A candidate key that is an alternative to the primary key.', aiExplanation: '辅助键/次要键：用于快速查找数据但不是主键的字段，通常用于建立索引。' },
  { id: getNextId(), chapterId: '8.1', term: 'Foreign key', definition: 'A set of attributes in one table that refer to the primary key in another table.', aiExplanation: '外键：一个表中的字段，它指向另一个表的主键，用于在两个表之间建立联系。' },
  { id: getNextId(), chapterId: '8.1', term: 'Relationship', definition: 'Situation in which one table in a database has a foreign key that refers to a primary key in another table in the database.', aiExplanation: '关系：数据库表与表之间的联系（如一对一、一对多）。' },
  { id: getNextId(), chapterId: '8.1', term: 'Referential integrity', definition: 'Property of a database that does not contain any values of a foreign key that are not matched to the corresponding primary key.', aiExplanation: '参照完整性：数据库的一种约束，保证外键引用的数据必须在主表中存在，防止出现“孤儿”记录。' },
  { id: getNextId(), chapterId: '8.1', term: 'Table', definition: 'A group of similar data, in a database, with rows for each instance of an entity and columns for each attribute.', aiExplanation: '表：数据库中存储数据的基本结构，由行和列组成。' },
  { id: getNextId(), chapterId: '8.1', term: 'Record (database)', definition: 'A row in a table in a database.', aiExplanation: '记录：表中的一行数据，包含一个实体的所有属性值。' },
  { id: getNextId(), chapterId: '8.1', term: 'Index (database)', definition: 'A data structure built from one or more columns in a database table to speed up searching for data.', aiExplanation: '索引：类似于书的目录，是一种能显著加快数据库查询速度的数据结构。' },
  { id: getNextId(), chapterId: '8.1', term: 'Entity-relationship (E-R) model or E-R diagram', definition: 'A graphical representation of a database and the relationships between the entities.', aiExplanation: 'E-R图（实体-关系图）：用于设计数据库结构的图表，直观展示实体、属性以及它们之间的关系。' },
  { id: getNextId(), chapterId: '8.1', term: 'Normalisation (database)', definition: 'The process of organising data to be stored in a database into two or more tables and relationships between the tables, so that data redundancy is minimised.', aiExplanation: '规范化：优化数据库结构的过程，通过拆分表来减少数据冗余和异常。' },
  { id: getNextId(), chapterId: '8.1', term: 'First normal form (1NF)', definition: 'The status of a relational database in which entities do not contain repeated groups of attributes.', aiExplanation: '第一范式 (1NF)：要求表中的所有字段都是原子性的，不可再分，且没有重复组。' },
  { id: getNextId(), chapterId: '8.1', term: 'Second normal form (2NF)', definition: 'The status of a relational database in which entities are in 1NF and any non-key attributes depend upon the primary key.', aiExplanation: '第二范式 (2NF)：在1NF基础上，消除非主键字段对主键的部分依赖（即必须完全依赖整个主键）。' },
  { id: getNextId(), chapterId: '8.1', term: 'Third normal form (3NF)', definition: 'The status of a relational database in which entities are in 2NF and all non-key attributes are independent.', aiExplanation: '第三范式 (3NF)：在2NF基础上，消除非主键字段之间的传递依赖（即非主键字段不能相互依赖）。' },
  { id: getNextId(), chapterId: '8.1', term: 'Composite key', definition: 'A set of attributes that form a primary key to provide a unique identifier for a table.', aiExplanation: '复合键：由两个或多个字段共同组成的主键，用于联合唯一标识一条记录。' },

  // 8.2 DBMS
  { id: getNextId(), chapterId: '8.2', term: 'Database management system (DBMS)', definition: 'Systems software for the definition, creation and manipulation of a database.', aiExplanation: '数据库管理系统 (DBMS)：用于创建、管理和操作数据库的软件（如MySQL、Oracle）。' },
  { id: getNextId(), chapterId: '8.2', term: 'Data management', definition: 'The organisation and maintenance of data in a database to provide the information required.', aiExplanation: '数据管理：对数据进行收集、存储、保护和使用的全过程管理。' },
  { id: getNextId(), chapterId: '8.2', term: 'Data dictionary', definition: 'A set of data that contains metadata (data about other data) for a database.', aiExplanation: '数据字典：描述数据库本身结构的数据（元数据），如表名、字段类型、约束条件等。' },
  { id: getNextId(), chapterId: '8.2', term: 'Developer interface', definition: 'Feature of a DBMS that provides developers with the commands required for definition, creation and manipulation of a database.', aiExplanation: '开发者接口：DBMS提供的工具或API，允许程序员编写代码来操作数据库。' },
  { id: getNextId(), chapterId: '8.2', term: 'Structured query language (SQL)', definition: 'The standard query language used with relational databases for data definition and data modification.', aiExplanation: '结构化查询语言 (SQL)：与关系型数据库通信的标准语言，用于查、增、删、改数据。' },
  { id: getNextId(), chapterId: '8.2', term: 'Data modelling', definition: 'The analysis and definition of the data structures required in a database and to produce a data model.', aiExplanation: '数据建模：在建立数据库前，规划和设计数据结构及关系的过程。' },
  { id: getNextId(), chapterId: '8.2', term: 'Logical schema', definition: 'A data model for a specific database that is independent of the DBMS used to build that database.', aiExplanation: '逻辑模式：数据库的逻辑结构设计，不依赖于具体的物理存储方式或特定的DBMS软件。' },
  { id: getNextId(), chapterId: '8.2', term: 'Access rights (database)', definition: 'The permissions given to database users to access, modify or delete data.', aiExplanation: '访问权限：控制不同用户对数据库能做什么操作（如只读、可写、管理员）的设置。' },
  { id: getNextId(), chapterId: '8.2', term: 'Query processor', definition: 'Feature of a DBMS that processes and executes queries written in structured query language (SQL)', aiExplanation: '查询处理器：DBMS中负责解析、优化和执行SQL命令的组件。' },

  // 8.3 DDL and DML
  { id: getNextId(), chapterId: '8.3', term: 'Data definition language (DDL)', definition: 'A language used to create, modify and remove the data structures that form a database.', aiExplanation: '数据定义语言 (DDL)：SQL中用于定义数据库结构（如创建表、修改列）的命令（如CREATE, DROP）。' },
  { id: getNextId(), chapterId: '8.3', term: 'Data manipulation language (DML)', definition: 'A language used to add, modify, delete and retrieve the data stored in a relational database.', aiExplanation: '数据操作语言 (DML)：SQL中用于操作实际数据（如插入、更新、查询）的命令（如SELECT, INSERT）。' },
  { id: getNextId(), chapterId: '8.3', term: 'SQL script', definition: 'A list of SQL commands that perform a given task, often stored in a file for reuse.', aiExplanation: 'SQL脚本：包含一系列SQL命令的文本文件，可批量执行以完成复杂的数据库任务。' },

  // 9.1 Computational thinking skills
  { id: getNextId(), chapterId: '9.1', term: 'Abstraction', definition: 'The process of extracting information that is essential, while ignoring what is not relevant, for the provision of a solution.', aiExplanation: '抽象：忽略无关细节，提取核心特征的过程（如画地铁图时刻意忽略实际地理弯曲，只保留站点连接）。' },
  { id: getNextId(), chapterId: '9.1', term: 'Decomposition', definition: 'The process of breaking a complex problem into smaller parts.', aiExplanation: '分解：将一个复杂大问题拆解成多个易于管理和解决的小问题。' },
  { id: getNextId(), chapterId: '9.1', term: 'Pattern recognition', definition: 'The identification of parts of a problem that are similar and could use the same solution.', aiExplanation: '模式识别：发现问题中的规律或相似之处，以便套用已有的解决方案。' },

  // 9.2 Algorithms
  { id: getNextId(), chapterId: '9.2', term: 'Structured English', definition: 'A method of showing the logical steps in an algorithm, using an agreed subset of straightforward English words for commands and mathematical operations.', aiExplanation: '结构化英语：一种介于自然语言和编程代码之间的描述方式，用受限的英语词汇描述算法逻辑。' },
  { id: getNextId(), chapterId: '9.2', term: 'Flowchart', definition: 'A diagrammatic representation of an algorithm.', aiExplanation: '流程图：用图形符号（如框、箭头）直观表示算法步骤的图表。' },
  { id: getNextId(), chapterId: '9.2', term: 'Algorithm', definition: 'An ordered set of steps to be followed in the completion of a task.', aiExplanation: '算法：解决特定问题的明确、有限的步骤序列。' },
  { id: getNextId(), chapterId: '9.2', term: 'Pseudocode', definition: 'A method of showing the detailed logical steps in an algorithm, using keywords, identifiers with meaningful names, and mathematical operators.', aiExplanation: '伪代码：类似编程语言但不需要严格语法的算法描述方式，侧重于逻辑而非语法，方便人类阅读。' },
  { id: getNextId(), chapterId: '9.2', term: 'Stepwise refinement', definition: 'The practice of subdividing each part of a larger problem into a series of smaller parts, and so on, as required.', aiExplanation: '逐步求精：一种自顶向下的设计方法，从高层概括开始，逐步深入细节，直到能写出代码。' },

  // 10.1 Data types and structures
  { id: getNextId(), chapterId: '10.1', term: 'Data type', definition: 'A classification attributed to an item of data, which determines the types of value it can take and how it can be used.', aiExplanation: '数据类型：数据的分类（如整数、字符串、布尔值），决定了数据占多少内存以及能进行什么运算。' },
  { id: getNextId(), chapterId: '10.1', term: 'Identifier', definition: 'A unique name applied to an item of data.', aiExplanation: '标识符：变量、函数或数组的名字，用于在代码中引用它们。' },
  { id: getNextId(), chapterId: '10.1', term: 'Record (data type)', definition: 'A composite data type comprising several related items that may be of different data types.', aiExplanation: '记录：一种复合数据结构，可以将不同类型的数据组合在一起（如一个“学生”记录包含姓名字符串和年龄整数）。' },
  { id: getNextId(), chapterId: '10.1', term: 'Composite data type', definition: 'A data type constructed using several of the basic data types available in a particular programming language.', aiExplanation: '复合数据类型：由基本数据类型组合而成的复杂类型（如数组、类、结构体）。' },
  { id: getNextId(), chapterId: '10.1', term: 'Array', definition: 'A data structure containing several elements of the same data type.', aiExplanation: '数组：存储一组相同类型数据的集合，通过索引（下标）访问。' },
  { id: getNextId(), chapterId: '10.1', term: 'Index (array)', definition: 'A numerical indicator of an item of data\'s position in an array.', aiExplanation: '索引/下标：数组中元素的位置编号，通常从0开始。' },
  { id: getNextId(), chapterId: '10.1', term: 'Lower bound', definition: 'The index of the first element in an array, usually 0 or 1.', aiExplanation: '下界：数组允许的最小索引值。' },
  { id: getNextId(), chapterId: '10.1', term: 'Upper bound', definition: 'The index of the last element in an array.', aiExplanation: '上界：数组允许的最大索引值。' },
  { id: getNextId(), chapterId: '10.1', term: 'Linear search', definition: 'A method of searching in which each element of an array is checked in order.', aiExplanation: '线性查找：最简单的查找算法，从头到尾一个接一个地比对，直到找到目标。' },
  { id: getNextId(), chapterId: '10.1', term: 'Bubble sort', definition: 'A method of sorting data in an array into alphabetical or numerical order by comparing adjacent items and swapping them if they are in the wrong order.', aiExplanation: '冒泡排序：一种基础排序算法，重复比较相邻元素并交换位置，像气泡一样把最大/最小值推到一端。' },
  { id: getNextId(), chapterId: '10.1', term: 'File', definition: 'A collection of data stored by a computer program to be used again.', aiExplanation: '文件：存储在辅助存储器（如硬盘）上的数据集合。' },
  { id: getNextId(), chapterId: '10.1', term: 'Abstract data type (ADT)', definition: 'A collection of data and a set of operations on that data.', aiExplanation: '抽象数据类型 (ADT)：一种逻辑上的数据模型（如栈、队列），定义了数据及对其的操作，但不关心具体实现细节。' },
  { id: getNextId(), chapterId: '10.1', term: 'Stack', definition: 'A list containing several items operating on the last in, first out (LIFO) principle.', aiExplanation: '栈：一种“后进先出”的数据结构，像叠盘子，最后放进去的必须最先拿出来。' },
  { id: getNextId(), chapterId: '10.1', term: 'Queue', definition: 'A list containing several items operating on the first in, first out (FIFO) principle.', aiExplanation: '队列：一种“先进先出”的数据结构，像排队买票，先来的先服务。' },
  { id: getNextId(), chapterId: '10.1', term: 'Linked list', definition: 'A list containing several items in which each item in the list points to the next item in the list.', aiExplanation: '链表：一种动态数据结构，每个元素包含数据和指向下一个元素的指针，像铁链一样串起来。' },

  // 11.1 Programming basics
  { id: getNextId(), chapterId: '11.1', term: 'Constant', definition: 'A named value that cannot change during the execution of a program.', aiExplanation: '常量：在程序运行过程中数值固定不变的量（如Pi）。' },
  { id: getNextId(), chapterId: '11.1', term: 'Variable', definition: 'A named value that can change during the execution of a program.', aiExplanation: '变量：在程序运行过程中数值可以改变的量，用于存储临时数据。' },
  { id: getNextId(), chapterId: '11.1', term: 'Function', definition: 'A set of statements that can be grouped together and easily called in a program whenever required, rather than repeating all of the statements each time. Unlike a procedure, a function always returns a value.', aiExplanation: '函数：一段执行特定任务并返回结果的代码块，可重复调用。' },
  { id: getNextId(), chapterId: '11.1', term: 'Library routine', definition: 'A tested and ready-to-use routine available in the development system of a programming language that can be incorporated into a program.', aiExplanation: '库函数：编程语言提供的标准代码模块，开发者可以直接使用而无需重新编写。' },
  { id: getNextId(), chapterId: '11.1', term: 'Procedure', definition: 'A set of statements that can be grouped together and easily called in a program whenever required, rather than repeating all of the statements each time.', aiExplanation: '过程：类似于函数，也是执行特定任务的代码块，但通常不返回结果（视语言定义而定）。' },

  // 11.3 Structured programming
  { id: getNextId(), chapterId: '11.3', term: 'Parameter', definition: 'A variable applied to a procedure or function that allows one to pass in a value for the procedure to use.', aiExplanation: '参数：函数定义时用于接收外部传入数据的占位符变量。' },
  { id: getNextId(), chapterId: '11.3', term: 'By value', definition: 'A method of passing a parameter to a procedure in which the value of the variable cannot be changed by the procedure.', aiExplanation: '值传递：将数据的副本传给函数，函数内部修改不会影响原本的变量。' },
  { id: getNextId(), chapterId: '11.3', term: 'By reference', definition: 'A method of passing a parameter to a procedure in which the value of the variable can be changed by the procedure.', aiExplanation: '引用传递：将数据的地址（引用）传给函数，函数内部的修改会直接改变外部原始变量。' },
  { id: getNextId(), chapterId: '11.3', term: 'Header (procedure or function)', definition: 'The first statement in the definition of a procedure or function, which contains its name, any parameters passed to it, and, for a function, the type of the return value.', aiExplanation: '函数头：函数定义的第一行，声明了函数名、参数列表和返回值类型。' },
  { id: getNextId(), chapterId: '11.3', term: 'Argument', definition: 'The value passed to a procedure or function.', aiExplanation: '参数值（实参）：调用函数时实际传递给它的具体数值或变量。' },

  // 12.1 Program development lifecycle
  { id: getNextId(), chapterId: '12.1', term: 'Program development lifecycle', definition: 'The process of developing a program set out in five stages: analysis, design, coding, testing and maintenance.', aiExplanation: '程序开发生命周期 (PDLC)：软件开发的全过程，包括分析、设计、编码、测试和维护五个阶段。' },
  { id: getNextId(), chapterId: '12.1', term: 'Analysis', definition: 'Part of the program development lifecycle; a process of investigation, leading to the specification of what a program is required to do.', aiExplanation: '分析阶段：搞清楚用户到底想要什么，确定软件的需求规格。' },
  { id: getNextId(), chapterId: '12.1', term: 'Design', definition: 'Part of the program development lifecycle; it uses the program specification from the analysis stage to show how the program should be developed.', aiExplanation: '设计阶段：规划软件的结构、算法和界面，决定“怎么做”。' },
  { id: getNextId(), chapterId: '12.1', term: 'Coding', definition: 'Part of the program development lifecycle; the writing of the program or suite of programs.', aiExplanation: '编码阶段：程序员编写实际代码来实现设计方案。' },
  { id: getNextId(), chapterId: '12.1', term: 'Testing', definition: 'Part of the program development lifecycle; the testing of the program to make sure that it works under all conditions.', aiExplanation: '测试阶段：查找并修复软件中的Bug，确保其按预期工作。' },
  { id: getNextId(), chapterId: '12.1', term: 'Maintenance', definition: 'Part of the program development lifecycle; the process of making sure that the program continues to work during use.', aiExplanation: '维护阶段：软件发布后的修补漏洞、更新功能和优化性能。' },
  { id: getNextId(), chapterId: '12.1', term: 'Waterfall model', definition: 'A linear sequential program development cycle, in which each stage is completed before the next is begun.', aiExplanation: '瀑布模型：一种传统的线性开发模式，按顺序一步步完成，不允许回头，适合需求明确的项目。' },
  { id: getNextId(), chapterId: '12.1', term: 'Iterative model', definition: 'A type of program development cycle in which a simple subset of the requirements is developed, then expanded or enhanced, with the development cycle being repeated until the full system has been developed.', aiExplanation: '迭代模型：先开发一个简易版本，然后不断循环改进和增加功能，直到完善。' },
  { id: getNextId(), chapterId: '12.1', term: 'Rapid application development (RAD)', definition: 'A type of program development cycle in which different parts of the requirements are developed in parallel, using prototyping to provide early user involvement in testing.', aiExplanation: '快速应用开发 (RAD)：通过快速制作原型和用户反馈来加速开发，强调速度和适应性。' },

  // 12.2 Program design
  { id: getNextId(), chapterId: '12.2', term: 'Structure chart', definition: 'A modelling tool used to decompose a problem into a set of sub-tasks. It shows the hierarchy or structure of the different modules and how they connect and interact with each other.', aiExplanation: '结构图：一种自顶向下的图表，展示系统模块的层级关系和调用顺序。' },
  { id: getNextId(), chapterId: '12.2', term: 'Finite state machine (FSM)', definition: 'A mathematical model of a machine that can be in one state of a fixed set of possible states; one state is changed to another by an external input; this is known as a transition.', aiExplanation: '有限状态机 (FSM)：一种计算模型，描述系统在不同状态之间如何根据输入进行转换（如自动售货机的逻辑）。' },
  { id: getNextId(), chapterId: '12.2', term: 'State-transition diagram', definition: 'A diagram showing the behaviour of a finite state machine (FSM).', aiExplanation: '状态转换图：用圆圈和箭头直观展示状态机工作逻辑的图表。' },
  { id: getNextId(), chapterId: '12.2', term: 'State-transition table', definition: 'A table showing every state of a finite state machine (FSM), each possible input and the state after the input.', aiExplanation: '状态转换表：用表格形式列出状态机所有可能的状态转换规则。' },

  // 12.3 Program testing and maintenance
  { id: getNextId(), chapterId: '12.3', term: 'Trace table', definition: 'A table showing the process of dry-running a program with columns showing the values of each variable as it changes.', aiExplanation: '追踪表：一种用于手动调试的表格，记录程序每一步执行后变量值的变化。' },
  { id: getNextId(), chapterId: '12.3', term: 'Run-time error', definition: 'An error found in a program when it is executed; the program may halt unexpectedly.', aiExplanation: '运行时错误：程序在运行过程中发生的错误（如除以零），会导致程序崩溃。' },
  { id: getNextId(), chapterId: '12.3', term: 'Test strategy', definition: 'An overview of the testing required to meet the requirements specified for a particular program; it shows how and when the program is to be tested.', aiExplanation: '测试策略：宏观的测试计划，规定了测试的方法、工具和时间安排。' },
  { id: getNextId(), chapterId: '12.3', term: 'Test plan', definition: 'A detailed list showing all the stages of testing and every test that will be performed for a particular program.', aiExplanation: '测试计划：详细的文档，列出了具体要进行的每一个测试用例。' },
  { id: getNextId(), chapterId: '12.3', term: 'Dry run', definition: 'A method of testing a program that involves working through a program or module from a program manually.', aiExplanation: '干跑/人工走查：程序员在纸上或脑子里模拟程序运行，手动检查逻辑。' },
  { id: getNextId(), chapterId: '12.3', term: 'Walkthrough', definition: 'A method of testing a program. A formal version of a dry run using pre-defined test cases.', aiExplanation: '代码走查：一种正式的代码审查会议，由同行一起检查代码逻辑。' },
  { id: getNextId(), chapterId: '12.3', term: 'Normal test data', definition: 'Test data that should be accepted by a program.', aiExplanation: '正常测试数据：符合预期的有效数据，程序应该能正常处理。' },
  { id: getNextId(), chapterId: '12.3', term: 'Abnormal test data', definition: 'Test data that should be rejected by a program.', aiExplanation: '异常测试数据：无效或错误格式的数据（如输入字母代替数字），程序应该拒绝并报错。' },
  { id: getNextId(), chapterId: '12.3', term: 'Extreme test data', definition: 'Test data that is on the limit of that accepted by a program.', aiExplanation: '极端/边界测试数据：处于有效范围边缘的数据（如最大值、最小值），用于检测边界条件。' },
  { id: getNextId(), chapterId: '12.3', term: 'Boundary test data', definition: 'Test data that is on the limit of that accepted by a program or that is just outside the limit of that rejected by a program.', aiExplanation: '边界测试数据：特指刚好在边界上或刚好越过边界的数据，是测试中最容易出问题的地方。' },
  { id: getNextId(), chapterId: '12.3', term: 'White-box testing', definition: 'A method of testing a program that tests the structure and logic of every path through a program module.', aiExplanation: '白盒测试：测试人员能看到内部代码结构，针对代码逻辑路径进行测试。' },
  { id: getNextId(), chapterId: '12.3', term: 'Black-box testing', definition: 'A method of testing a program that tests a module\'s inputs and outputs.', aiExplanation: '黑盒测试：测试人员不看内部代码，只关注输入和输出是否符合需求功能。' },
  { id: getNextId(), chapterId: '12.3', term: 'Integration testing', definition: 'A method of testing a program that tests combinations of program modules that work together.', aiExplanation: '集成测试：将各个模块组合在一起进行测试，确保它们接口兼容，能协同工作。' },
  { id: getNextId(), chapterId: '12.3', term: 'Stub testing', definition: 'The use of dummy modules for testing purposes.', aiExplanation: '桩测试：用简单的占位程序（桩）代替尚未完成的模块，以便测试其他部分。' },
  { id: getNextId(), chapterId: '12.3', term: 'Alpha testing', definition: 'The testing of a completed or nearly completed program in-house by the development team.', aiExplanation: 'Alpha测试：软件开发内部进行的初步验收测试。' },
  { id: getNextId(), chapterId: '12.3', term: 'Beta testing', definition: 'The testing of a completed program by a small group of users before it is released.', aiExplanation: 'Beta测试：发布给选定的外部用户进行的测试，用于收集真实环境下的反馈。' },
  { id: getNextId(), chapterId: '12.3', term: 'Acceptance testing', definition: 'The testing of a completed program to prove to the customer that it works as required.', aiExplanation: '验收测试：由客户进行的最终测试，以确认软件满足合同要求并决定是否接收。' },
  { id: getNextId(), chapterId: '12.3', term: 'Corrective maintenance', definition: 'The correction of any errors that appear during use.', aiExplanation: '纠错性维护：修复软件发布后发现的Bug。' },
  { id: getNextId(), chapterId: '12.3', term: 'Perfective maintenance', definition: 'The process of making improvements to the performance of a program.', aiExplanation: '完善性维护：为了提升性能或用户体验而修改软件。' },
  { id: getNextId(), chapterId: '12.3', term: 'Adaptive maintenance', definition: 'The alteration of a program to perform new tasks.', aiExplanation: '适应性维护：为了适应新环境（如新系统、新硬件）而修改软件。' }
];